using System.ComponentModel;
using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Builder;
using OpenVersus.Server.Core.Settings;

namespace OpenVersus.Server.Core.FileStorage;

/// <summary>Where the game fetches this server's own images (the TS server's /assets/ routes).</summary>
public sealed class AssetsSettings
{
    [Description("The host in asset download URLs when a request has no Host header (GAME_DOMAIN).")]
    public string Domain { get; set; } = "localhost";
}

/// <summary>
/// GET /file_storage and /file_storage/{slug} (TS handlers/file_storage.ts): the game's file records (art for the
/// carousels and store). Two records are this server's own, the client-update art, whose download URL is this
/// server's /assets/ URL as the request reached it; they are filled from templates (FileStorage/*.json, markers
/// {{assets}}, and {{update-keyart}}/{{update-thumbnail}} in the list). The other records are the same for everyone
/// (Static/file-storage-{slug}.json), their download URLs WB's expired S3 links as the TS server has them. All
/// generated by tools/access/gen_templates.mjs.
/// </summary>
public static class FileStorageResponses
{
    public const string UpdateKeyart = "openversus-update-required-keyart";
    public const string UpdateThumbnail = "openversus-update-required-thumbnail";

    /// <summary>The slugs with a record of their own that is the same for everyone.</summary>
    public static readonly IReadOnlySet<string> StaticSlugs = new HashSet<string>(StringComparer.Ordinal)
    {
        "beginnermode-carousel-keyart", "beginnermode-carousel-thumbnail", "harley-rift-s5-keyart", "harley-rift-s5-thumbnail",
        "s5-bp-carousel-keyart", "s5-bp-carousel-thumbnail", "t-discord-qa-carousel-keyart", "t-discord-qa-carousel-thumbnail",
        "wonderwoman-arena-keyart", "wonderwoman-arena-thumbnail",
    };

    private static readonly Lazy<string> s_list = new(() => Template("file-storage-list"));
    private static readonly Lazy<string> s_keyart = new(() => Template("file-storage-update-keyart"));
    private static readonly Lazy<string> s_thumbnail = new(() => Template("file-storage-update-thumbnail"));

    /// <summary>The file list; <paramref name="assetsUrl"/> is this server's /assets/ URL, ending in a slash.</summary>
    public static JsonNode List(string assetsUrl)
    {
        var list = JsonNode.Parse(s_list.Value)!.AsArray();
        for (int i = 0; i < list.Count; i++)
        {
            if (list[i]?.GetValueKind() == System.Text.Json.JsonValueKind.String && list[i]!.GetValue<string>() is { } marker)
            {
                list[i] = marker switch
                {
                    "{{update-keyart}}" => UpdateRecord(UpdateKeyart, assetsUrl),
                    "{{update-thumbnail}}" => UpdateRecord(UpdateThumbnail, assetsUrl),
                    _ => throw new InvalidOperationException($"file-storage-list.json has a marker nothing fills: {marker}"),
                };
            }
        }

        return list;
    }

    /// <summary>One of the two client-update records.</summary>
    public static JsonNode UpdateRecord(string slug, string assetsUrl)
    {
        var record = JsonNode.Parse(slug switch
        {
            UpdateKeyart => s_keyart.Value,
            UpdateThumbnail => s_thumbnail.Value,
            _ => throw new ArgumentOutOfRangeException(nameof(slug), slug, "not a client-update record"),
        })!.AsObject();
        record["download_url"] = ((string)record["download_url"]!).Replace("{{assets}}", assetsUrl, StringComparison.Ordinal);
        return record;
    }

    private static string Template(string name)
    {
        using var stream = typeof(FileStorageResponses).Assembly.GetManifestResourceStream($"OpenVersus.Server.Core.FileStorage.{name}.json")
            ?? throw new InvalidOperationException($"FileStorage/{name}.json is not embedded");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    public static WebApplicationBuilder AddFileStorage(this WebApplicationBuilder builder)
    {
        builder.AddSetting<AssetsSettings>("Assets");
        return builder;
    }
}
