import { getAssetsByType } from "../../loadAssets";
import type { JWT_CLAIMS } from "../../middleware/middlewares";

export const access_static_data = (
  profileIcon: string,
  token: string,
  account: JWT_CLAIMS,
  wsEndpoint: string,
) => ({
  token: token,
  in_queue: false,
  configuration: {
    gcm: { enabled: null, project_number: null },
    gpgs: { google_play_client_id: null },
    apns: { enabled: null, environment: null, sha1: null },
    server_side_code_deploy: {
      sha: "5a98f8bc35424a1bcfaab95d51f8ef40afb83c9c",
      instance: "a5bc65aa-b129-4f8c-8fc9-b7d20a392463",
    },
    realtime: {
      enabled: true,
      "default-cluster": "ec2-us-east-1-dokken",
      servers: {
        "ec2-us-east-1-dokken": {
          "mvsi-realtime": { ws: wsEndpoint, udp: "0.0.0.0:0" },
        },
      },
    },
    auth: { override_client_restrictions: false },
  },
  achievements: [],
  account: {
    updated_at: { _hydra_unix_date: 1742265239 },
    created_at: { _hydra_unix_date: 1674508668 },
    deleted: false,
    orphaned: false,
    orphaned_reason: null,
    public_id: account.id,
    identity: {
      avatar: "https://s3.amazonaws.com/wb-agora-hydra-ugc-dokken/identicons/identicon.584.png",
      default_username: true,
      personal_data: {},
      alternate: {
        wb_network: [
          {
            id: account.id,
            username: account.username,
            avatar: null,
            email: null,
          },
        ],
        steam: [
          {
            id: "76561195177950872",
            username: account.username,
            avatar: "https://avatars.steamstatic.com/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb.jpg",
            email: null,
          },
        ],
      },
      usernames: [
        { auth: "hydra", username: "dark-wild-grass-voice-yrpu2" },
        { auth: "steam", username: account.username },
        { auth: "wb_network", username: account.username },
      ],
      platforms: ["steam"],
      current_platform: "steam",
      is_cross_platform: false,
      username: "dark-wild-grass-voice-yRPU2",
    },
    email_verification: { state: "unverified" },
    opt_ins: { wbplay_optin: false },
    auth: {
      wb_network: [
        {
          id: account.id,
          created_at: { _hydra_unix_date: 1674508668 },
        },
      ],
    },
    wb_account: {
      completed: true,
      age_category: "adult",
      email_verified: false,
    },
    external_accounts: {},
    privacy_levels: {
      presence: { state: "default" },
      clan: { invitation: "default" },
      match: { invitation: "default" },
      relationship: { follow: "default" },
    },
    points: 0,
    state: "normal",
    restriction_status: {},
    wbplay_data_synced: false,
    wbplay_identity: null,
    state_data: {},
    locale: "en-US",
    data: {
      EULAAcceptTimestamp: 1674508690,
      EULAAcceptVersion: 5,
      LastLoginPlatform: "EPlatform::PC",
      LastPlayedCharacterSlug: "character_C018",
    },
    server_data: {
      LastLogoutTime: "2023-03-14T17:44:29.198Z",
      RestedXP: 300,
      ProfileIcon: {
        Slug: `${profileIcon}`,
        AssetPath: getAssetsByType("ProfileIconData").find((p) => p.slug === profileIcon)
          ?.assetPath,
      },
      LastLoginTime: "Tue Mar 14 2023 00:14:29 GMT+0000 (Coordinated Universal Time)",
      AntiCheatServerKick: 2,
      OpenBeta: true,
      LastLoginPlatform: "PC",
      LastWeeklyRefresh: { _hydra_unix_date: 1741694400 },
      LastDailyRefresh: { _hydra_unix_date: 1742212800 },
      Transforms: {
        GoldStatTracker: true,
        OpenBetaFreebies: true,
        BannerKnightSlugFixed: true,
        UpgradeWarMakeGood_8_5_2024: { _hydra_unix_date: 1722992854 },
        Season2CharactersInMasterCalculated: true,
        Season3PrestigeFix: true,
        CharacterCurrencyRoundUp: { _hydra_unix_date: 1731440253 },
        MmrSeason4: true,
        Season4FighterRoadPromo: true,
        Season4Promo: true,
        Season4FixRolloverRp: true,
        ShaggySkinMakeGoodS4: { _hydra_unix_date: 1731713281 },
        SeasonFourAcademiaMakeGood: { _hydra_unix_date: 1734104356 },
        SeasonFourAcademiaMakeGoodScoreGranted: 0,
        Season4RankedRewardCatchup: true,
        FixRankedCharactersInGold: true,
      },
      RetroactiveRiftBattlepassPayoutTime: { _hydra_unix_date: 1719246277 },
      LastRefreshSeason: "Season:SeasonFive",
      LastKnownDebugDelta: 0,
      LastRefreshBattlepassEvent: "evt_battlepass_season_five",
    },
    server_owner_data: {},
    id: account.id,
    connections: [
      {
        id: token,
        start_time: 1742265239,
        last_used: 1742265239,
        realtime_start_time: 0,
        realtime_end_time: 0,
        metadata: "`\u00010\bPlatform0\u0002PC",
        status: {
          environment: { id: "620d88aae6bbaf409686b6fc" },
          current_environment: true,
        },
      },
    ],
    presence_state: 1,
    presence: "online",
  },
  profile: {
    updated_at: { _hydra_unix_date: 1742265241 },
    account_id: account.id,
    created_at: { _hydra_unix_date: 1674508668 },
    last_login: { _hydra_unix_date: 1742265239 },
    points: null,
    data: {
      IsChildAccount: false,
      PerkPreferences: {
        Characters: {
          character_jake: {
            LastSelectedPage: 0,
            PerkPages: [
              {
                PageName: "CUSTOM 1",
                PerkSlugs: ["", "", "", ""],
              },
            ],
          },
          character_arya: {
            LastSelectedPage: 0,
            PerkPages: [
              {
                PageName: "CUSTOM 1",
                PerkSlugs: ["", "", "", ""],
              },
            ],
          },
          character_superman: {
            LastSelectedPage: 0,
            PerkPages: [
              {
                PageName: "CUSTOM 1",
                PerkSlugs: ["", "", "", ""],
              },
            ],
          },
          character_garnet: {
            LastSelectedPage: 0,
            PerkPages: [
              {
                PageName: "CUSTOM 1",
                PerkSlugs: ["", "", "", ""],
              },
            ],
          },
          character_finn: {
            LastSelectedPage: 0,
            PerkPages: [
              {
                PageName: "CUSTOM 1",
                PerkSlugs: ["", "", "", ""],
              },
            ],
          },
          character_C018: {
            LastSelectedPage: 0,
            PerkPages: [
              {
                PageName: "CUSTOM 1",
                PerkSlugs: ["", "", "", ""],
              },
            ],
          },
          character_tom_and_jerry: {
            LastSelectedPage: 0,
            PerkPages: [
              {
                PageName: "CUSTOM 1",
                PerkSlugs: ["", "", "", ""],
              },
            ],
          },
          character_wonder_woman: {
            LastSelectedPage: 0,
            PerkPages: [
              {
                PageName: "CUSTOM 1",
                PerkSlugs: ["", "", "", ""],
              },
            ],
          },
        },
      },
      HasCompletedFirstMatch: true,
      HasCompletedFTUE: true,
      MostRecentlyViewedCurrentRiftSeason: "Season:SeasonFour",
    },
    server_data: {
      debug_all_unlocked: 0,
      Level: 1,
      CurrentXP: 0,
      MatchConfig: {
        MultiqueueConfigs: [
          {
            QueueType: "Unranked",
            Context: "Matchmade",
            TeamStyle: "Duos",
            GameModeAlias: "Versus",
          },
        ],
      },
      //BattlepassID: "63cef9c6609607a8deb2c31d",
      stat_trackers: {
        HighestDamageDealt: 656,
        TotalRingoutLeader: 22,
        TotalRingouts: 13448,
        TotalWins: 3132,
        character_highest_damage_dealt: {
          character_arya: 18,
          character_superman: 18,
          character_shaggy: 459,
          character_Jason: 656,
          character_C018: 167,
          character_c16: 310,
          character_wonder_woman: 524,
        },
        character_ringouts: {
          character_arya: 3,
          character_superman: 3,
          character_Jason: 13368,
          character_C018: 3,
          character_shaggy: 43,
          character_c16: 3,
          character_wonder_woman: 25,
        },
        character_total_damage_dealt: {
          character_arya: 41,
          character_superman: 60,
          character_shaggy: 4483.185760498047,
          character_Jason: 1407299.925918579,
          character_C018: 295,
          character_c16: 310,
          character_wonder_woman: 3285,
        },
        character_wins: {
          character_arya: 2,
          character_superman: 1,
          character_finn: 4,
          character_C018: 3,
          character_tom_and_jerry: 1,
          character_shaggy: 60,
          character_Jason: 3053,
          character_c16: 1,
          character_wonder_woman: 7,
        },
        TotalAttacksDodged: 46204,
        Valentines2023Currency: 5200,
        character_matches: {
          character_shaggy: 68,
          character_BananaGuard: 1,
          character_Jason: 5608,
          character_C018: 2,
          character_c16: 1,
          character_wonder_woman: 9,
        },
        season1: {
          HighestDamageDealt: 131.25,
          TotalWins: 2,
          character_highest_damage_dealt: { character_shaggy: 131.25 },
          character_matches: {
            character_shaggy: 2,
            character_BananaGuard: 1,
          },
          character_total_damage_dealt: {
            character_shaggy: 199.18576049804688,
          },
          character_wins: { character_shaggy: 2 },
        },
        season2: {
          HighestDamageDealt: 546.0574951171875,
          TotalAttacksDodged: 19596,
          TotalRingouts: 5774,
          TotalWins: 1349,
          character_highest_damage_dealt: {
            character_Jason: 546.0574951171875,
          },
          character_matches: { character_Jason: 2409 },
          character_ringouts: { character_Jason: 5774 },
          character_total_damage_dealt: {
            character_Jason: 545648.9259185791,
          },
          character_wins: { character_Jason: 1349 },
          ranked: {
            "1v1": { Wins: 779, CharactersInGold: 1 },
            "2v2": { CharactersInGold: 1 },
          },
          TotalRingoutLeader: 12,
          TotalAssists: 32,
          TotalDoubleRingouts: 6,
        },
        TotalToastsGiven: 706,
        TotalToastsReceived: 706,
        TotalAssists: 48,
        TotalDoubleRingouts: 18,
        season3: {
          HighestDamageDealt: 591,
          TotalAttacksDodged: 12501,
          TotalRingouts: 3957,
          TotalWins: 920,
          character_highest_damage_dealt: { character_Jason: 591 },
          character_matches: { character_Jason: 1600 },
          character_ringouts: { character_Jason: 3957 },
          character_total_damage_dealt: { character_Jason: 379634 },
          character_wins: { character_Jason: 920 },
          ranked: { "1v1": { Wins: 404, CharactersInGold: 1 } },
          TotalDoubleRingouts: 7,
          TotalRingoutLeader: 3,
        },
        season4: {
          HighestDamageDealt: 643,
          TotalAttacksDodged: 10418,
          TotalRingouts: 2785,
          character_highest_damage_dealt: {
            character_Jason: 643,
            character_C018: 167,
          },
          character_matches: { character_Jason: 1217, character_C018: 2 },
          character_ringouts: { character_Jason: 2782, character_C018: 3 },
          character_total_damage_dealt: {
            character_Jason: 370542,
            character_C018: 295,
          },
          TotalWins: 599,
          character_wins: { character_Jason: 598, character_C018: 1 },
          ranked: { "1v1": { Wins: 242, CharactersInGold: 1 } },
          TotalAssists: 2,
          TotalDoubleRingouts: 1,
          TotalRingoutLeader: 1,
        },
        season5: {
          ranked: { "1v1": { CharactersInGold: 1, Wins: 80 } },
          HighestDamageDealt: 656,
          TotalAttacksDodged: 3684,
          TotalRingouts: 926,
          character_highest_damage_dealt: {
            character_Jason: 656,
            character_shaggy: 459,
            character_c16: 310,
            character_wonder_woman: 524,
          },
          character_matches: {
            character_Jason: 382,
            character_shaggy: 66,
            character_c16: 1,
            character_wonder_woman: 9,
          },
          character_ringouts: {
            character_Jason: 855,
            character_shaggy: 43,
            character_c16: 3,
            character_wonder_woman: 25,
          },
          character_total_damage_dealt: {
            character_Jason: 111475,
            character_shaggy: 4284,
            character_c16: 310,
            character_wonder_woman: 3285,
          },
          TotalWins: 252,
          character_wins: {
            character_Jason: 186,
            character_shaggy: 58,
            character_c16: 1,
            character_wonder_woman: 7,
          },
          TotalRingoutLeader: 4,
          TotalDoubleRingouts: 4,
          TotalAssists: 14,
        },
      },
      ftue: { current_ftue_step: "eDONE" },
      OpenBeta: true,
      HasReceivedBattlepassRewardFromOpenBeta: true,
      SeasonalData: {
        "Season:SeasonTwo": {
          Ranked: {
            DataByMode: {
              "1v1": {
                BestCharacter: {
                  CurrentPoints: 2709,
                  MaxPoints: 2745,
                  GamesPlayed: 2270,
                  SetsPlayed: 1317,
                  CharacterSlug: "character_Jason",
                  LastUpdateTimestamp: { _hydra_unix_date: 1721968544 },
                },
                DataByCharacter: {
                  character_Jason: {
                    CurrentPoints: 2709,
                    MaxPoints: 2745,
                    GamesPlayed: 2270,
                    SetsPlayed: 1317,
                    Wins: 753,
                    Losses: 752,
                    DamageDealt: 518935,
                    DamageTaken: 670230,
                    Ringouts: 5496,
                    Deaths: 4941,
                    LastUpdateTimestamp: { _hydra_unix_date: 1726551460 },
                    LastDecayMs: 0,
                  },
                },
                GamesPlayed: 2272,
                LastUpdateTimestamp: { _hydra_unix_date: 1726551460 },
                SetsPlayed: 1318,
                FinalLeaderboardRank: 745,
              },
              "2v2": {
                BestCharacter: {
                  CurrentPoints: 1035,
                  MaxPoints: 1047,
                  GamesPlayed: 107,
                  SetsPlayed: 48,
                  CharacterSlug: "character_Jason",
                  LastUpdateTimestamp: { _hydra_unix_date: 1724119352 },
                },
                DataByCharacter: {
                  character_Jason: {
                    CurrentPoints: 1035,
                    MaxPoints: 1047,
                    GamesPlayed: 107,
                    SetsPlayed: 48,
                    Wins: 25,
                    Losses: 26,
                    DamageDealt: 18082,
                    DamageTaken: 26826,
                    Ringouts: 193,
                    Deaths: 177,
                    LastUpdateTimestamp: { _hydra_unix_date: 1724517900 },
                    LastDecayMs: 0,
                  },
                },
                GamesPlayed: 107,
                LastUpdateTimestamp: { _hydra_unix_date: 1724517900 },
                SetsPlayed: 48,
                FinalLeaderboardRank: 37414,
              },
            },
            ClaimedRewards: [
              "EC1B6F59453B11272D24DD94189FC209",
              "BB3E4B7048C823BE345B8F86CCBCCA84",
              "89709B1442BF36DD11BD98BCFB0D4AF1",
              "40B4F0174999C47FEAD0CE91419BBC7B",
              "B67EDC654607F8583E06978841798205",
              "8519085948FD7C75D380A9B4646A2306",
              "F2A63E5C406E3D13D9C5BCB0CCBDE371",
              "AD47AB5D491ACF00EF52289735A8B493",
              "684E91904181C8F3636BE38CF4B0E3C6",
              "C8C6CD8140A6E7A30F589CB10E677113",
            ],
            bEndOfSeasonRewardsGranted: true,
          },
        },
        "Season:SeasonThree": {
          Ranked: {
            DataByMode: {
              "1v1": {
                DataByCharacter: {
                  character_Jason: {
                    CurrentPoints: 2858,
                    MaxPoints: 2929,
                    GamesPlayed: 1591,
                    SetsPlayed: 672,
                    Wins: 404,
                    Losses: 403,
                    DamageDealt: 376835,
                    DamageTaken: 481079,
                    Ringouts: 3929,
                    Deaths: 3411,
                    LastUpdateTimestamp: { _hydra_unix_date: 1731366640 },
                    LastDecayMs: 0,
                  },
                },
                GamesPlayed: 1591,
                SetsPlayed: 672,
                BestCharacter: {
                  CurrentPoints: 2858,
                  MaxPoints: 2929,
                  GamesPlayed: 1591,
                  SetsPlayed: 672,
                  CharacterSlug: "character_Jason",
                  LastUpdateTimestamp: { _hydra_unix_date: 1726623581 },
                },
                LastUpdateTimestamp: { _hydra_unix_date: 1731366640 },
                FinalLeaderboardRank: 857,
              },
              "2v2": {
                DataByCharacter: {
                  character_Jason: {
                    CurrentPoints: 35,
                    MaxPoints: 35,
                    GamesPlayed: 0,
                    SetsPlayed: 0,
                    Wins: 0,
                    Losses: 0,
                    DamageDealt: 0,
                    DamageTaken: 0,
                    Ringouts: 0,
                    Deaths: 0,
                    LastUpdateTimestamp: { _hydra_unix_date: 1726623581 },
                    LastDecayMs: 0,
                  },
                },
                GamesPlayed: 0,
                SetsPlayed: 0,
                BestCharacter: {
                  CurrentPoints: 35,
                  MaxPoints: 35,
                  GamesPlayed: 0,
                  SetsPlayed: 1,
                  CharacterSlug: "character_Jason",
                  LastUpdateTimestamp: { _hydra_unix_date: 1726623581 },
                },
                FinalLeaderboardRank: 129774,
              },
            },
            ClaimedRewards: [
              "B67EDC654607F8583E06978841798205",
              "F2A63E5C406E3D13D9C5BCB0CCBDE371",
              "AD47AB5D491ACF00EF52289735A8B493",
              "684E91904181C8F3636BE38CF4B0E3C6",
              "C8C6CD8140A6E7A30F589CB10E677113",
            ],
            bEndOfSeasonRewardsGranted: true,
          },
        },
        "Season:SeasonFour": {
          LastLoginDay: { _hydra_unix_date: 1738281600 },
          NumDaysLoggedIn: 27,
          NumLogins: 45,
          Ranked: {
            DataByMode: {
              "1v1": {
                DataByCharacter: {
                  character_Jason: {
                    CurrentPoints: 2457,
                    MaxPoints: 2605,
                    GamesPlayed: 1189,
                    SetsPlayed: 493,
                    Wins: 238,
                    Losses: 239,
                    DamageDealt: 361469,
                    DamageTaken: 379378,
                    Ringouts: 2713,
                    Deaths: 2780,
                    LastUpdateTimestamp: { _hydra_unix_date: 1738356298 },
                    LastDecayMs: 0,
                  },
                },
                GamesPlayed: 1189,
                SetsPlayed: 493,
                BestCharacter: {
                  CurrentPoints: 2457,
                  MaxPoints: 2605,
                  GamesPlayed: 1189,
                  SetsPlayed: 493,
                  CharacterSlug: "character_Jason",
                  LastUpdateTimestamp: { _hydra_unix_date: 1731512851 },
                },
                LastUpdateTimestamp: { _hydra_unix_date: 1738356298 },
                FinalLeaderboardRank: 694,
              },
            },
            ClaimedRewards: [
              "B67EDC654607F8583E06978841798205",
              "F2A63E5C406E3D13D9C5BCB0CCBDE371",
              "AD47AB5D491ACF00EF52289735A8B493",
              "684E91904181C8F3636BE38CF4B0E3C6",
              "C8C6CD8140A6E7A30F589CB10E677113",
            ],
            bEndOfSeasonRewardsGranted: true,
          },
        },
        "Season:SeasonFive": {
          LastLoginDay: { _hydra_unix_date: 1742256000 },
          NumDaysLoggedIn: 21,
          NumLogins: 206,
          Ranked: {
            DataByMode: {
              "1v1": {
                DataByCharacter: {
                  character_Jason: {
                    CurrentPoints: 2137,
                    MaxPoints: 2179,
                    GamesPlayed: 371,
                    SetsPlayed: 160,
                    Wins: 80,
                    Losses: 79,
                    DamageDealt: 109764,
                    DamageTaken: 120253,
                    Ringouts: 837,
                    Deaths: 856,
                    LastUpdateTimestamp: { _hydra_unix_date: 1740903312 },
                    LastDecayMs: 0,
                  },
                },
                GamesPlayed: 371,
                SetsPlayed: 160,
                BestCharacter: {
                  CurrentPoints: 2137,
                  MaxPoints: 2179,
                  GamesPlayed: 371,
                  SetsPlayed: 160,
                  CharacterSlug: "character_Jason",
                  LastUpdateTimestamp: { _hydra_unix_date: 1738983225 },
                },
                LastUpdateTimestamp: { _hydra_unix_date: 1740903312 },
              },
            },
            ClaimedRewards: [
              "D17B128B40B9A1A73A8602A9D25A1A3A",
              "C8C6CD8140A6E7A30F589CB10E677113",
              "BB3E4B7048C823BE345B8F86CCBCCA84",
              "F2A63E5C406E3D13D9C5BCB0CCBDE371",
              "EC1B6F59453B11272D24DD94189FC209",
              "0D5B77894611BDDA93E815BCFEE03AE8",
              "B67EDC654607F8583E06978841798205",
            ],
          },
        },
      },
    },
    server_owner_data: {},
    inventory: {},
    matches: {},
    cross_match_results: {},
    notifications: {},
    aggregates: {},
    calculations: {},
    files: [],
    user_segments: [],
    random_distribution: 0.25115115419482414,
    id: account.id,
  },
  notifications: [],
  maintenance: null,
  wb_network: { network_token: token },
});
