import type { ArenaConstants, ArenaData } from "../lobby/arena.lobby.types";
import type { Region } from "../matchmaking/matchmaking.matching";
import type { ContainerTemplate, SERVER_MODESTRING } from "../matchmaking/matchmaking.types";
import type { PlayerConfig } from "../playerConfig/playerConfig.types";

export type GameplayConfig = {
  ArenaId?: string;
  ArenaConstants?: ArenaConstants;
  ArenaData?: ArenaData;
  GameplayConfig: MatchConfig;
};

export type ActiveMatch = {
  matchKey: string;
  fromLobbyId: string;
  GameplayConfig: GameplayConfig;
  state: string;
  createdAt: number;
  template: ContainerTemplate;
};
type CustomGameSettings = {
  bHazardsEnabled: boolean;
  bShieldsEnabled: boolean;
  MatchTime: number;
  NumRingouts: number;
};
type HudSettings = {
  bDisplayPortraits: boolean;
  bDisplayStocks: boolean;
  bDisplayTimer: boolean;
};
type MatchConfig = {
  ArenaModeInfo: {
    FaceoffWaitTime: number;
    bReadyToStart: boolean;
    ShopTime: number;
  } | null;
  RiftNodeId: string;
  ScoreEvaluationRule: string;
  bIsPvP: boolean;
  ScoreAttributionRule: string;
  MatchDurationSeconds: number;
  Created: Date;
  EventQueueSlug: string;
  bModeGrantsProgress: boolean;
  TeamData: unknown[];
  Spectators: unknown;
  bIsRanked: boolean;
  bIsCustomGame: boolean;
  Players: { [key: string]: PlayerConfig };
  CustomGameSettings: CustomGameSettings;
  HudSettings: HudSettings;
  bIsCasualSpecial: boolean;
  bAllowMapHazards: boolean;
  RiftNodeAttunement: string;
  CountdownDisplay: string;
  Cluster: Region;
  WorldBuffs: string[];
  bIsTutorial: boolean;
  MatchId: string;
  bIsOnlineMatch: boolean;
  ModeString: SERVER_MODESTRING;
  Map: string;
  bIsRift: boolean;
};

export type EndOfMatchStats = {
  WinningTeamIndex: number;
  Score: number[];
  PlayerMissionUpdates: Record<string, MatchStats>;
  PlayerNetworkStats: Record<string, number>;
};

export type MatchHistory = {
  id: string;
  updatedAt: Date;
  createdAt: Date;
  completion_time: Date;
  win: string[];
  loss: string[];
  draw: boolean;
  server_data: {
    GameplayConfig: GameplayConfig;
  };
  players: {
    all: MatchHistoryPlayer[];
  };
  cluster: string;
  template: {
    id: string;
    slug: string;
    created_at: Date;
    updated_at: Date;
  };
  access: string;
};

export type MatchHistoryPlayer = {
  account_id: string;
  reported_results: {
    win: string[];
    loss: string[];
    draw: boolean;
  };
  data: {
    EndOfMatchStats: EndOfMatchStats;
  };
  identity: {
    avatar: string;
    default_username: boolean;
  };
};

export type MatchStats = {
  "Fighter:AgentSmith:Silence": number;
  "Fighter:AgentSmith:TeleAlly": number;
  "Fighter:BananaGuard:Buff": number;
  "Fighter:BananaGuard:Facebox": number;
  "Fighter:Batman:GrappleAlly": number;
  "Fighter:C025:lenoregrab": number;
  "Fighter:Finn:AirPojectileDestroy": number;
  "Fighter:Finn:BuyBmo": number;
  "Fighter:Garnet:FullBuff": number;
  "Fighter:Harley:BombSave": number;
  "Fighter:IronGiant:RageMission": number;
  "Fighter:Jason:RageHit": number;
  "Fighter:Jerry:AllyAttach": number;
  "Fighter:Lebron:Defense": number;
  "Fighter:Lebron:Pass": number;
  "Fighter:Marvin:ReverseProjectile": number;
  "Fighter:Marvin:bubble": number;
  "Fighter:Morty:AllySave": number;
  "Fighter:Morty:SplitNade": number;
  "Fighter:Reindog:IceCleanse": number;
  "Fighter:Reindog:LoveLeashAlly": number;
  "Fighter:Rick:AllySeed": number;
  "Fighter:Rick:PortalKB": number;
  "Fighter:Shaggy:EnragedAttackUsed": number;
  "Fighter:Shaggy:FinishedCombo": number;
  "Fighter:Shaggy:RageBuildComplete": number;
  "Fighter:Shaggy:SandwichHeal": number;
  "Fighter:Steven:Bubblestack": number;
  "Fighter:Steven:EnemyBubble": number;
  "Fighter:Taz:Chicken": number;
  "Fighter:Taz:Eat": number;
  "Hitbox:Stripe:Kickflip": number;
  "Hitbox:Velma:GrabAlly": number;
  "Hitbox:Velma:Van": number;
  "Marceline:Powerslide": number;
  "Objective:Match:Boss:M015:Defeated": number;
  "Objective:Match:Character:BugsBunny:HealSandwich": number;
  "Objective:Match:Character:Stripe:Gun": number;
  "Objective:Match:Character:WonderWoman:AllyLasso": number;
  "Objective:Match:Character:WonderWoman:FullChargeBubble": number;
  "Objective:Match:Enemies:AcmeSkyDronesDestroyed": number;
  "Objective:Match:Enemies:BuffApplied:Chicken": number;
  "Objective:Match:Enemies:BuffApplied:Frozen": number;
  "Objective:Match:Enemies:BuffApplied:Ignited": number;
  "Objective:Match:Enemies:BuffApplied:Shocked": number;
  "Objective:Match:Enemies:BuffApplied:Silence": number;
  "Objective:Match:Enemies:BuffApplied:Weakened": number;
  "Objective:Match:Hazards:SafetySpotlightAttacksDodged": number;
  "Objective:Match:Hazards:SafetySpotlightAttacksTaken": number;
  "Objective:Match:Hazards:SafetySpotlightHitsOutsideSpotlight": number;
  "Objective:Match:Hazards:TravelTube:HitOpponentsInto": number;
  "Objective:Match:Map:M007:EmblemOpened": number;
  "Objective:Match:PlayCoOp": number;
  "Objective:Match:PopAllyBubble": number;
  "Objective:Match:Rifts:LazarusPit:BuffedRingouts": number;
  "Objective:Match:Rifts:LazarusPit:FellIn": number;
  "Objective:Match:Rifts:LazarusPit:TempHealth": number;
  "Objective:Match:Special:DefenseHealth": number;
  "Objective:Match:Special:DefenseHealth:CollectEvidence": number;
  "Objective:Match:Special:DoorPortalEnemy": number;
  "Objective:Match:Special:DoorPortalProjectile": number;
  "Objective:Match:Special:GalleryBalloonsDestroyed": number;
  "Objective:Match:Special:GalleryTargetsDestroyed": number;
  "Objective:Match:Special:GhostHitOpponent": number;
  "Objective:Match:Special:GhostHitSelf": number;
  "Objective:Match:Special:GoblinTreasureCollected": number;
  "Objective:Match:Special:GoblinTreasureCollected:Rare": number;
  "Objective:Match:Special:GolfCount": number;
  "Objective:Match:Special:GolfHolesCompleted": number;
  "Objective:Match:Special:JumpRopeJumps": number;
  "Objective:Match:Special:RacePlacement": number;
  "Objective:Match:Special:ShmupEnemyDestroyed": number;
  "Objective:Match:Special:ShootingGalleryScore": number;
  "Objective:Match:Special:TargetsDestroyed": number;
  "Objective:Match:Special:TreasureCollected": number;
  "Objective:Match:Special:VolleyballShutout": number;
  "Stat:Game:Character:DebuffsCleansed": number;
  "Stat:Game:Character:Stock:DamageTaken": number;
  "Stat:Game:Character:TotalAirAttacksHit": number;
  "Stat:Game:Character:TotalAirAttacksUsed": number;
  "Stat:Game:Character:TotalAirDamageDealt": number;
  "Stat:Game:Character:TotalAirNormalsHit": number;
  "Stat:Game:Character:TotalAirNormalsUsed": number;
  "Stat:Game:Character:TotalAirSpecialsHit": number;
  "Stat:Game:Character:TotalAirSpecialsUsed": number;
  "Stat:Game:Character:TotalAirTime": number;
  "Stat:Game:Character:TotalArmorBreaks": number;
  "Stat:Game:Character:TotalArmorHitsTaken": number;
  "Stat:Game:Character:TotalAssists": number;
  "Stat:Game:Character:TotalAttackDamageDealt": number;
  "Stat:Game:Character:TotalAttacksDodged": number;
  "Stat:Game:Character:TotalAttacksHit": number;
  "Stat:Game:Character:TotalAttacksParried": number;
  "Stat:Game:Character:TotalAttacksUsed": number;
  "Stat:Game:Character:TotalChargeAttacksHit": number;
  "Stat:Game:Character:TotalChargeAttacksUsed": number;
  "Stat:Game:Character:TotalCooldownAbilitiesStarted": number;
  "Stat:Game:Character:TotalCrouchTime": number;
  "Stat:Game:Character:TotalDamageAdded": number;
  "Stat:Game:Character:TotalDamageDealt": number;
  "Stat:Game:Character:TotalDamageDodged": number;
  "Stat:Game:Character:TotalDamageMitigated": number;
  "Stat:Game:Character:TotalDamageParried": number;
  "Stat:Game:Character:TotalDamageTaken": number;
  "Stat:Game:Character:TotalDashAttacksHit": number;
  "Stat:Game:Character:TotalDashAttacksUsed": number;
  "Stat:Game:Character:TotalDirectionalAirDodgesUsed": number;
  "Stat:Game:Character:TotalDirectionalDodgesUsed": number;
  "Stat:Game:Character:TotalDirectionalGroundDodgesUsed": number;
  "Stat:Game:Character:TotalDodgesUsed": number;
  "Stat:Game:Character:TotalDoubleJumps": number;
  "Stat:Game:Character:TotalDoubleRingouts": number;
  "Stat:Game:Character:TotalDownAirNormalHit": number;
  "Stat:Game:Character:TotalDownAirNormalUsed": number;
  "Stat:Game:Character:TotalDownAirSpecialsHit": number;
  "Stat:Game:Character:TotalDownAirSpecialsUsed": number;
  "Stat:Game:Character:TotalDownGroundNormalHit": number;
  "Stat:Game:Character:TotalDownGroundNormalUsed": number;
  "Stat:Game:Character:TotalDownGroundSpecialsHit": number;
  "Stat:Game:Character:TotalDownGroundSpecialsUsed": number;
  "Stat:Game:Character:TotalDownNormalAttacksHit": number;
  "Stat:Game:Character:TotalDownNormalAttacksUsed": number;
  "Stat:Game:Character:TotalDownRingouts": number;
  "Stat:Game:Character:TotalDownSpecialsHit": number;
  "Stat:Game:Character:TotalDownSpecialsUsed": number;
  "Stat:Game:Character:TotalDownspikeRingouts": number;
  "Stat:Game:Character:TotalElectricAttacksHit": number;
  "Stat:Game:Character:TotalFireAttacksHit": number;
  "Stat:Game:Character:TotalFullyChargedAttacksHit": number;
  "Stat:Game:Character:TotalGreyHealthReceived": number;
  "Stat:Game:Character:TotalGroundAttacksHit": number;
  "Stat:Game:Character:TotalGroundAttacksUsed": number;
  "Stat:Game:Character:TotalGroundDamageDealt": number;
  "Stat:Game:Character:TotalGroundNormalsHit": number;
  "Stat:Game:Character:TotalGroundNormalsUsed": number;
  "Stat:Game:Character:TotalGroundSpecialsHit": number;
  "Stat:Game:Character:TotalGroundSpecialsUsed": number;
  "Stat:Game:Character:TotalHealingReceived": number;
  "Stat:Game:Character:TotalHitsTaken": number;
  "Stat:Game:Character:TotalIceAttacksHit": number;
  "Stat:Game:Character:TotalJumps": number;
  "Stat:Game:Character:TotalKnockbackAdded": number;
  "Stat:Game:Character:TotalKnockbackMitigated": number;
  "Stat:Game:Character:TotalLeftRingouts": number;
  "Stat:Game:Character:TotalNeutralAirDodgesUsed": number;
  "Stat:Game:Character:TotalNeutralAirNormalHit": number;
  "Stat:Game:Character:TotalNeutralAirNormalUsed": number;
  "Stat:Game:Character:TotalNeutralAirSpecialsHit": number;
  "Stat:Game:Character:TotalNeutralAirSpecialsUsed": number;
  "Stat:Game:Character:TotalNeutralDodgesUsed": number;
  "Stat:Game:Character:TotalNeutralGroundDodgesUsed": number;
  "Stat:Game:Character:TotalNeutralGroundNormalHit": number;
  "Stat:Game:Character:TotalNeutralGroundNormalUsed": number;
  "Stat:Game:Character:TotalNeutralGroundSpecialsHit": number;
  "Stat:Game:Character:TotalNeutralGroundSpecialsUsed": number;
  "Stat:Game:Character:TotalNeutralNormalAttacksHit": number;
  "Stat:Game:Character:TotalNeutralNormalAttacksUsed": number;
  "Stat:Game:Character:TotalNeutralSpecialsHit": number;
  "Stat:Game:Character:TotalNeutralSpecialsUsed": number;
  "Stat:Game:Character:TotalNormalAttacksHit": number;
  "Stat:Game:Character:TotalNormalAttacksUsed": number;
  "Stat:Game:Character:TotalPlatformDropThroughs": number;
  "Stat:Game:Character:TotalProjectileRingouts": number;
  "Stat:Game:Character:TotalProjectilesBlocked": number;
  "Stat:Game:Character:TotalProjectilesReflected": number;
  "Stat:Game:Character:TotalRightRingouts": number;
  "Stat:Game:Character:TotalRingouts": number;
  "Stat:Game:Character:TotalRingoutsEnemyLowPercent": number;
  "Stat:Game:Character:TotalRingoutsReceived": number;
  "Stat:Game:Character:TotalRingoutsWithLessDamage": number;
  "Stat:Game:Character:TotalRingoutsWithMoreDamage": number;
  "Stat:Game:Character:TotalShieldBreaksFromShieldBreaker": number;
  "Stat:Game:Character:TotalSideAirNormalHit": number;
  "Stat:Game:Character:TotalSideAirNormalUsed": number;
  "Stat:Game:Character:TotalSideAirSpecialsHit": number;
  "Stat:Game:Character:TotalSideAirSpecialsUsed": number;
  "Stat:Game:Character:TotalSideGroundNormalHit": number;
  "Stat:Game:Character:TotalSideGroundNormalUsed": number;
  "Stat:Game:Character:TotalSideGroundSpecialsHit": number;
  "Stat:Game:Character:TotalSideGroundSpecialsUsed": number;
  "Stat:Game:Character:TotalSideNormalAttacksHit": number;
  "Stat:Game:Character:TotalSideNormalAttacksUsed": number;
  "Stat:Game:Character:TotalSideSpecialsHit": number;
  "Stat:Game:Character:TotalSideSpecialsUsed": number;
  "Stat:Game:Character:TotalSpecialDamageDealt": number;
  "Stat:Game:Character:TotalSpecialsHit": number;
  "Stat:Game:Character:TotalSpecialsUsed": number;
  "Stat:Game:Character:TotalSweetSpotsHit": number;
  "Stat:Game:Character:TotalTauntsUsed": number;
  "Stat:Game:Character:TotalUpAirNormalHit": number;
  "Stat:Game:Character:TotalUpAirNormalUsed": number;
  "Stat:Game:Character:TotalUpAirSpecialsHit": number;
  "Stat:Game:Character:TotalUpAirSpecialsUsed": number;
  "Stat:Game:Character:TotalUpGroundNormalHit": number;
  "Stat:Game:Character:TotalUpGroundNormalUsed": number;
  "Stat:Game:Character:TotalUpGroundSpecialsHit": number;
  "Stat:Game:Character:TotalUpGroundSpecialsUsed": number;
  "Stat:Game:Character:TotalUpNormalAttacksHit": number;
  "Stat:Game:Character:TotalUpNormalAttacksUsed": number;
  "Stat:Game:Character:TotalUpRingouts": number;
  "Stat:Game:Character:TotalUpSpecialsHit": number;
  "Stat:Game:Character:TotalUpSpecialsUsed": number;
  "Stat:Game:Character:TotalWalkLeftTime": number;
  "Stat:Game:Character:TotalWalkRightTime": number;
  "Stat:Game:Character:TotalWalkTime": number;
  "Stat:Game:Character:TotalWallHangTime": number;
};
