#!/usr/bin/env python3
"""Writes haproxy.cfg from docs/routes.json: the game's one URL, split by route owner.

The game talks to one host and port. Each route in routes.json names the service that owns it (access, social,
lobbies, matchflow, web, or http for the rest), so the router sends a request to that service by its path alone: no
path has two owners (checked here), which also keeps x-hydra-http-method out of the routing. Exact paths are matched
before templates ({id} segments become one path segment), and anything unlisted goes to the http service, as the game
API's catch-all. Run from the repository's dotnet/ directory:

    python3 deploy/router/generate.py            writes deploy/router/haproxy.cfg
    python3 deploy/router/generate.py --check    exits 1 if the file on disk is not what routes.json gives

The services are reached by their Compose names and default ports; the bench override changes nothing here.
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROUTES = HERE.parent.parent / "docs" / "routes.json"
OUT = HERE / "haproxy.cfg"

BACKENDS = {
    "http": "http:8000",
    "access": "access:8001",
    "social": "social:8002",
    "lobbies": "lobbies:8003",
    "web": "web:8004",
    "matchflow": "matchflow:8005",
}
DEFAULT = "http"


def template_regex(path: str) -> str:
    """A route template as HAProxy's regex: {x} is one segment; the one regex route (/.*/access) is kept as written."""
    if path == "/.*/access":
        return "^/[^/]+/access$"
    parts = [("[^/]+" if p.startswith("{") and p.endswith("}") else re.escape(p)) for p in path.split("/")]
    return "^" + "/".join(parts) + "$"


def main(check: bool) -> int:
    routes = json.loads(ROUTES.read_text())
    owners: dict[str, set[str]] = defaultdict(set)
    for r in routes:
        owners[r["path"]].add(r["owner"])
    clashes = {p: sorted(o) for p, o in owners.items() if len(o) > 1}
    if clashes:
        sys.exit(f"routes.json: a path with two owners cannot be routed by path: {clashes}")
    unknown = sorted({o for s in owners.values() for o in s} - BACKENDS.keys())
    if unknown:
        sys.exit(f"routes.json names owners this generator has no backend for: {unknown}")

    exact = sorted((p, next(iter(o))) for p, o in owners.items() if "{" not in p and p != "/.*/access")
    templates = sorted((p, next(iter(o))) for p, o in owners.items() if "{" in p or p == "/.*/access")
    by_owner_exact: dict[str, list[str]] = defaultdict(list)
    for p, o in exact:
        if o != DEFAULT:
            by_owner_exact[o].append(p)
    by_owner_templates: dict[str, list[str]] = defaultdict(list)
    for p, o in templates:
        if o != DEFAULT:
            by_owner_templates[o].append(template_regex(p))

    lines = [
        "# Generated by deploy/router/generate.py from docs/routes.json. Do not edit; regenerate.",
        f"# {len(owners)} paths: {len(exact)} exact, {len(templates)} templates; unlisted paths go to {DEFAULT}.",
        "",
        "global",
        "    log stdout format raw local0",
        "    maxconn 4096",
        "",
        "# Compose recreates a service container with a new address; the names are resolved through Docker's DNS as they",
        "# change, not once at startup.",
        "resolvers docker",
        "    nameserver dns 127.0.0.11:53",
        "    resolve_retries 3",
        "    timeout resolve 1s",
        "    timeout retry 1s",
        "    hold valid 10s",
        "    hold other 10s",
        "    hold refused 10s",
        "    hold nx 10s",
        "    hold timeout 10s",
        "    hold obsolete 10s",
        "",
        "defaults",
        "    mode http",
        "    log global",
        "    option httplog",
        "    option forwardfor",
        "    option http-server-close",
        "    timeout connect 5s",
        "    timeout client 60s",
        "    timeout server 60s",
        "    # The game holds long polls and large hiss answers; the services, not the router, decide how long a request may take.",
        "",
        "frontend game",
        "    bind *:8000",
        "    # The services take the client's address from X-Real-IP (else X-Forwarded-Host, else the last X-Forwarded-For hop),",
        "    # and bans key off it. Nothing sits ahead of this router, so what the client sent in those headers is dropped",
        "    # and the connection's own address written; forwardfor then appends it as the one X-Forwarded-For hop.",
        "    http-request del-header X-Forwarded-For",
        "    http-request del-header X-Forwarded-Host",
        "    http-request set-header X-Real-IP %[src]",
        "    # The services' health endpoints are for Docker and the router, not the public.",
        "    http-request deny status 404 if { path_beg /health/ }",
        "",
        "    # Exact paths first, one ACL per owner.",
    ]
    for owner in sorted(by_owner_exact):
        paths = by_owner_exact[owner]
        for i in range(0, len(paths), 8):
            lines.append(f"    acl exact_{owner} path " + " ".join(paths[i:i + 8]))
    lines.append("")
    lines.append("    # Then templates: a {segment} matches one path segment.")
    for owner in sorted(by_owner_templates):
        for rx in by_owner_templates[owner]:
            lines.append(f"    acl tmpl_{owner} path_reg {rx}")
    lines.append("")
    for owner in sorted(by_owner_exact):
        lines.append(f"    use_backend {owner} if exact_{owner}")
    for owner in sorted(by_owner_templates):
        lines.append(f"    use_backend {owner} if tmpl_{owner}")
    lines.append(f"    default_backend {DEFAULT}")
    lines.append("")
    for owner, address in BACKENDS.items():
        lines += [
            f"backend {owner}",
            "    option httpchk GET /health/live",
            f"    server {owner} {address} check inter 5s fall 3 rise 2 resolvers docker init-addr libc,none",
            "",
        ]
    text = "\n".join(lines)
    if check:
        if OUT.read_text() != text:
            print(f"{OUT} is out of date; run {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT}: {len(exact)} exact paths, {len(templates)} templates")
    return 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv[1:]))
