import { configDotenv } from "dotenv";
import { cleanEnv, str, num, bool } from "envalid";

configDotenv({ path: ".env" });

const env = cleanEnv(process.env, {
  BANNED_NAMES_FILE: str({ default: "../data/banned_names.txt" }),
  CIDR_BANS_FILE: str({ default: "../data/cidr_bans.txt" }),
  DATA_ASSET_TOKEN: str(),
  DEFAULT_ELO: num({ default: 1000 }),
  ELO_DIVISOR: num({ default: 800 }),
  EMULATE_P2: num({ default: 0 }),
  FORCE_CHANGE_NAMES_FILE: str({ default: "../data/force_change_names.txt" }),
  GAME_DOMAIN: str(),
  GAME_VERSION: str(),
  HTTP_PORT: num(),
  IP_BANS_FILE: str({ default: "../data/bans.txt" }),
  K_PROVISIONAL: num({ default: 64 }),
  K_1V1: num({ default: 32 }),
  K_2V2: num({ default: 24 }),
  LOCAL_PUBLIC_IP: str(),
  MONGODB_URI: str(),
  ON_DEMAND_ROLLBACK: num({ default: 0 }),
  ON_DEMAND_ROLLBACK_PORT_LOW: num({ default: 60000 }),
  ON_DEMAND_ROLLBACK_PORT_HIGH: num({ default: 64000 }),
  OVS_SERVER: str({ default: "http://localhost:8000" }),
  PROVISIONAL_GAME_THRESHOLD: num({ default: 20 }),
  REDIS: str(),
  REDIS_PORT: num(),
  REDIS_PW: str(),
  REDIS_USERNAME: str(),
  ROLLBACK_UDP_PORT_HIGH: num({ default: 57019 }),
  ROLLBACK_UDP_PORT_LOW: num({ default: 57000 }),
  USE_INTERNAL_ROLLBACK: num({ default: 0 }),
  USE_INTERNAL_ROLLBACK_CPP: num({ default: 0 }),
  UDP_PORT: num(),
  UDP_SERVER_IP: str(),
  UDP_SERVER_IP2: str(),
  VERBOSE_LOGGING: num({ default: 0 }),
  WEBHOOK_HMAC_SECRET: str({ default: "CHANGEME" }),
  WEBHOOK_HOST: str({ default: "localhost" }),
  WEBHOOK_PORT: num({ default: 9001 }),
  WEBHOOK_DEPLOY_PATH: str({ default: "/hooks/deploy-rollback-server"}),
  WEBHOOK_DESTROY_PATH: str({ default: "/hooks/destroy-rollback-server" }),
  DEPLOY_KEY: str({ default: "CHANGEME" }),
  DEPLOY_ROLLBACK_DEFAULTS_FILE: str({ default: "../data/deploy-rollback-defaults.json" }),
  WB_DOMAIN: str(),
  WEBSOCKET_PORT: num(),
});

export default env;
