using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using OpenVersus.Server.Core.Missions;
using OpenVersus.Server.Core.Settings;

namespace OpenVersus.Server.Core.Seasons;

// POST /ssc/invoke/attempt_daily_refresh: the game asks at login which season is current and when the next daily and
// weekly refreshes are. The answer is the TS server's (handlers/ssc.ts, handleSsc_invoke_attempt_daily_refresh) field for
// field, with CurrentSeason from the setting Season:Current instead of its fixed "Season:SeasonFive", and with
// Missions:Enabled the next resets the missions roll at (MissionClock) instead of a day and a week from now. The game lists
// the rift seasons up to the current one (the Season 6 rogue rifts need Season:SeasonSix); other per-season data the
// servers still key by Season 5 (ranked, leaderboards, the login's trackers) may need filling for Season 6: see
// docs/SEASONS.md.

/// <summary>Season settings.</summary>
public sealed class SeasonSettings
{
    [Description("The season the game is told is current (attempt_daily_refresh CurrentSeason), a gameplay tag: Season:SeasonFive, Season:SeasonSix, ...")]
    [RegularExpression("^Season:Season[A-Za-z]+$")]
    public string Current { get; set; } = "Season:SeasonSix";
}

public interface ISeasonService
{
    /// <summary>The attempt_daily_refresh answer.</summary>
    JsonObject DailyRefresh();
}

internal sealed class SeasonService(IOptionsMonitor<SeasonSettings> settings, IOptionsMonitor<MissionSettings> missions, TimeProvider time) : ISeasonService
{
    public JsonObject DailyRefresh()
    {
        var at = time.GetUtcNow();
        long now = at.ToUnixTimeSeconds();
        // With missions working, the resets they roll at (MissionClock); otherwise the TS server's day and week from now.
        var mission = missions.CurrentValue;
        long nextDaily = mission.Enabled ? MissionClock.NextDaily(mission, at).ToUnixTimeSeconds() : now + 86400;
        long nextWeekly = mission.Enabled ? MissionClock.NextWeekly(mission, at).ToUnixTimeSeconds() : now + 604800;
        return new JsonObject
        {
            ["body"] = new JsonObject
            {
                ["ServerTimeUtc"] = new JsonObject { ["_hydra_unix_date"] = now },
                ["CurrentSeason"] = settings.CurrentValue.Current,
                ["NextDailyRefreshTime"] = new JsonObject { ["_hydra_unix_date"] = nextDaily },
                ["NextWeeklyRefreshTime"] = new JsonObject { ["_hydra_unix_date"] = nextWeekly },
                ["FreeCharacterRotation"] = new JsonArray(),
                ["ReturnData"] = new JsonObject(),
                ["PlayerMissionObject"] = new JsonObject
                {
                    ["MissionControllerContainers"] = new JsonObject(),
                    ["ClaimLocks"] = new JsonObject(),
                },
            },
            ["metadata"] = null,
            ["return_code"] = 0,
        };
    }
}

/// <summary>
/// Profile SeasonalData for seasons the login's profile (the TS server's literal, login-response.json) has no entry for,
/// from a live export made while the service ran (seasonal-data.json, generated by tools/seasons/gen_seasonal_data.mjs;
/// the same account's data for every player, as the literal is). See docs/SEASONS.md.
/// </summary>
public static class SeasonalData
{
    /// <summary>The season whose ranked data every other season's is copied from (the ratings are not kept per season).</summary>
    public const string RankedSeason = "Season:SeasonFive";

    private static readonly Lazy<JsonObject> s_seasons = new(() =>
    {
        using var stream = typeof(SeasonalData).Assembly.GetManifestResourceStream("OpenVersus.Server.Core.Seasons.seasonal-data.json")
            ?? throw new InvalidOperationException("seasonal-data.json is not embedded");
        return JsonNode.Parse(stream)!.AsObject();
    });

    /// <summary>The profile's SeasonalData entry for <paramref name="season"/> (a copy), or null when there is none.</summary>
    public static JsonObject? For(string season) => s_seasons.Value[season]?.DeepClone().AsObject();

    /// <summary>
    /// Adds <paramref name="season"/>'s entry to a login profile's SeasonalData (profile.server_data.SeasonalData) when
    /// it has none and there is one to add; true when added.
    /// </summary>
    public static bool AddTo(JsonObject response, string season)
    {
        if (response["profile"]?["server_data"]?["SeasonalData"] is not JsonObject seasonal || seasonal.ContainsKey(season) || For(season) is not { } entry)
        {
            return false;
        }

        seasonal[season] = entry;
        return true;
    }
}

public static class SeasonHosting
{
    public static WebApplicationBuilder AddSeasons(this WebApplicationBuilder builder)
    {
        builder.AddSetting<SeasonSettings>("Season");
        builder.Services.AddSingleton<ISeasonService, SeasonService>();
        return builder;
    }
}
