import { getCurrentCRC, MATCHMAKING_CRC } from "../data/config";
import { EVENT_QUEUE_CONFIG } from "../data/eventQueue";
import { GAME_MODES_CONFIG } from "../data/gameModes";
import { GEMS_CONFIG } from "../data/gems";
import { GEMS_BUFF_CONFIG } from "../data/gemsBuffs";
import { INVENTORY_DEFINITIONS } from "../data/inventoryDefs";
import { MAP_ROTATIONS } from "../data/maps";
import { MILESTONE_REWARDS } from "../data/milestones";
import { MISSION_CONTAINER } from "../data/missionContainers";
import { MISSION_CONTROLLERS } from "../data/missionControllers";
import { MISSION_LIST } from "../data/missionList";
import { MISSION_OBJECTIVES } from "../data/missionObjectives";
import { MISSIONS_CONFIG } from "../data/missions";
import { PERKS_CONFIG } from "../data/perks";
import { PERKS_SET_CONFIG } from "../data/perksSet";
import { RANK_SETTINGS } from "../data/rankSettings";
import { RIFTS_CONFIG } from "../data/rifts";
import { XP_MULTIPLIER_CONFIG } from "../data/xpMultiplier";
import { getAllAssets, getAllSkinsByChar, getAllTauntsByChar, getAssetsByType } from "../loadAssets";

export function generate_hiss() {
  return {
    body: {
      Crc: getCurrentCRC(),
      MatchmakingCrc: MATCHMAKING_CRC,
      Data: {
        "game-mode-config": {
          _hydra_compressed: GAME_MODES_CONFIG,
        },
        "event-queue-config": {
          _hydra_compressed: EVENT_QUEUE_CONFIG,
        },
        "map-rotations": {
          _hydra_compressed: MAP_ROTATIONS,
        },
        "milestone-reward-tracks": {
          _hydra_compressed: MILESTONE_REWARDS,
        },
        "ranked-settings": {
          _hydra_compressed: RANK_SETTINGS,
        },
        "rift-config": {
          _hydra_compressed: RIFTS_CONFIG,
        },
        "xp-multiplier-components": {
          _hydra_compressed: XP_MULTIPLIER_CONFIG,
        },
        /*       "perk-config": {
        "_hydra_compressed": PERKS_CONFIG,
      }, */
        "gem-config": {
          _hydra_compressed: GEMS_CONFIG,
        },
        "gem-buff-config": {
          _hydra_compressed: GEMS_BUFF_CONFIG,
        },
        "perk-set-config": {
          _hydra_compressed: PERKS_SET_CONFIG,
        },
        "mission-containers": {
          _hydra_compressed: MISSION_CONTAINER,
        },
        "mission-controlers": {
          _hydra_compressed: MISSION_CONTROLLERS,
        },
        "mission-list": {
          _hydra_compressed: MISSION_LIST,
        },
        missions: {
          _hydra_compressed: MISSIONS_CONFIG,
        },
        "mission-objectives": {
          _hydra_compressed: MISSION_OBJECTIVES,
        },
        "prestige-lookup": {
          _hydra_compressed: {
            banner: {
              Uncommon: 50,
              Rare: 200,
              Epic: 700,
              Legendary: 3000,
              Prestige: 3000,
              Elusive: 200,
            },
            ring_out_vfx: {
              Uncommon: 250,
              Rare: 800,
              Epic: 2400,
              Legendary: 7200,
              Prestige: 7200,
              Elusive: 800,
            },
            skin: {
              Uncommon: 300,
              Rare: 960,
              Epic: 3600,
              Legendary: 9600,
              Prestige: 9600,
              Elusive: 960,
            },
            announcer_pack: {
              Uncommon: 50,
              Rare: 300,
              Epic: 1200,
              Legendary: 4800,
              Prestige: 4800,
              Elusive: 300,
            },
            profile_icon: {
              Uncommon: 15,
              Rare: 50,
              Epic: 200,
              Legendary: 800,
              Prestige: 800,
              Elusive: 50,
            },
            stat_tracking_bundle: {
              Uncommon: 100,
              Rare: 100,
              Epic: 500,
              Legendary: 2200,
              Prestige: 2200,
              Elusive: 100,
            },
            emote: {
              Uncommon: 25,
              Rare: 100,
              Epic: 500,
              Legendary: 2200,
              Prestige: 2200,
              Elusive: 100,
            },
            taunt: {
              Uncommon: 100,
              Rare: 350,
              Epic: 1000,
              Legendary: 4000,
              Prestige: 4000,
              Elusive: 350,
            },
          },
        },
        "feature-toggles": {
          _hydra_compressed: {
            IsSpectatorEnabled: true,
            IsRankedEnabled: false,
            LoadoutValidation: true,
            RetailMatchmakingCriteria: true,
            Perks: true,
            Gamelift: false,
            "Gamelift-1v1": false,
            "Gamelift-2v2": false,
            "Gamelift-PvE": false,
            "Gamelift-Custom": false,
            FTUE: true,
            TimedRiftDifficultyReleases: true,
            QueuedGameplaySessionInvites: true,
            RiftReleaseDates: true,
            IsRankedUIEnabled: false,
            IsRankedQueueEnabled: false,
            AlwaysEnterBots: false,
            FFA: true,
            IsBattlepassTiersSkipsEnabled: true,
            IsVariantMasteryEnabled: false,
            EnableForceReloadHydraUsersInFaceoff: true,
            EnableFeaturedBundlesInVariantSelect: true,
            AllowSelectingUnownedCharactersLocalPlay: true,
            IsFeaturedBundlesInCarouselEnabled: true,
            EnableBoostedSkinSurfacing: true,
            EndFtueOnCurrentSeason: true,
            EnableMonitorSwitchingFix: true,
            HissInvalidationKick: false,
            BeginnerMode: true,
            AutoParty: false,
            S3EogBackwardsCompatibility: true,
            EnableTileViewStoreArea: true,
            evtq_colbyqueue: false,
            SkipForceReloadingLocalPlayerProfile: true,
            IsFighterRoadEnabled: false,
            EnablePostMatchV2: true,
            Arena: false,
            IsStoreLayoutObjectPoolingEnabled: true,
            IsStoreWidgetPoolingEnabled: true,
            IsLabV2Enabled: true,
            ArenaShopLocalOperations: true,
            IsCustomGameGameModesEnabled: true,
            AlwaysAllowSkippingEoG: true,
            Carousel: true,
            FighterRoadV2: false,
            IsStoreBatchingEnabled: false,
            IsCustomGameMutatorsEnabled: true,
            GameServerMatchKeyFromNotify: true,
            SscCriticalCallEnabled: true,
            AreMissionNotificationsLimited: false,
            IsLocalHydraSavingEnabled: true,
            evtq_arena: false,
            evtq_1v1testinggrounds: false,
            evtq_2v2testinggrounds: false,
          },
        },
        "inventory-item-definitions": {
          _hydra_compressed: {}, //INVENTORY_DEFINITIONS,
        },
        "enabled-assets-data": {
          _hydra_compressed: {
            ClientAssetData: {
              AssetsThatMaybeFilteredOut: {
                CharacterSlugs: [],
                EmoteSlugs: [],
                BannerSlugs: [],
                RingoutVfxSlugs: [],
                ProfileIconSlugs: [],
                AnnouncerPackSlugs: [],
                StatTrackerSlugs: [],
                GemSlugs: [],
                PerkSlugs: [],
                SkinSlugsByCharacter: {
                  character_wonder_woman: {
                    Slugs: [],
                  },
                  character_velma: {
                    Slugs: [],
                  },
                  character_tom_and_jerry: {
                    Slugs: [],
                  },
                  character_superman: {
                    Slugs: [],
                  },
                  character_steven: {
                    Slugs: [],
                  },
                  character_shaggy: {
                    Slugs: [],
                  },
                  character_jake: {
                    Slugs: [],
                  },
                  character_harleyquinn: {
                    Slugs: [],
                  },
                  character_garnet: {
                    Slugs: [],
                  },
                  character_finn: {
                    Slugs: [],
                  },
                  character_creature: {
                    Slugs: [],
                  },
                  character_C028: {
                    Slugs: [],
                  },
                  character_C023B: {
                    Slugs: [],
                  },
                  character_C023A: {
                    Slugs: [],
                  },
                  character_C021: {
                    Slugs: [],
                  },
                  character_C020: {
                    Slugs: [],
                  },
                  character_c019: {
                    Slugs: [],
                  },
                  character_C018: {
                    Slugs: [],
                  },
                  character_C017: {
                    Slugs: [],
                  },
                  character_c16: {
                    Slugs: [],
                  },
                  character_taz: {
                    Slugs: [],
                  },
                  character_bugs_bunny: {
                    Slugs: [],
                  },
                  character_Jason: {
                    Slugs: [],
                  },
                  character_BananaGuard: {
                    Slugs: [],
                  },
                  character_arya: {
                    Slugs: [],
                  },
                  character_batman: {
                    Slugs: [],
                  },
                  character_c036: {
                    Slugs: [],
                  },
                  character_C030: {
                    Slugs: [],
                  },
                  character_C027: {
                    Slugs: [],
                  },
                  character_C026: {
                    Slugs: [],
                  },
                  character_c024: {
                    Slugs: [],
                  },
                  character_C025: {
                    Slugs: [],
                  },
                  character_C031: {
                    Slugs: [],
                  },
                  character_C029: {
                    Slugs: [],
                  },
                  character_c038: {
                    Slugs: [],
                  },
                },
                TauntSlugsByCharacter: {
                  character_wonder_woman: {
                    Slugs: [],
                  },
                  character_velma: {
                    Slugs: [],
                  },
                  character_tom_and_jerry: {
                    Slugs: [],
                  },
                  character_superman: {
                    Slugs: [],
                  },
                  character_steven: {
                    Slugs: [],
                  },
                  character_shaggy: {
                    Slugs: [],
                  },
                  character_jake: {
                    Slugs: [],
                  },
                  character_harleyquinn: {
                    Slugs: [],
                  },
                  character_garnet: {
                    Slugs: [],
                  },
                  character_finn: {
                    Slugs: [],
                  },
                  character_creature: {
                    Slugs: [],
                  },
                  character_C030: {
                    Slugs: [],
                  },
                  character_C023B: {
                    Slugs: [],
                  },
                  character_C023A: {
                    Slugs: [],
                  },
                  character_C021: {
                    Slugs: [],
                  },
                  character_C020: {
                    Slugs: [],
                  },
                  character_c019: {
                    Slugs: [],
                  },
                  character_C018: {
                    Slugs: [],
                  },
                  character_C017: {
                    Slugs: [],
                  },
                  character_c16: {
                    Slugs: [],
                  },
                  character_taz: {
                    Slugs: [],
                  },
                  character_bugs_bunny: {
                    Slugs: [],
                  },
                  character_batman: {
                    Slugs: [],
                  },
                  character_arya: {
                    Slugs: [],
                  },
                  character_Jason: {
                    Slugs: [],
                  },
                  character_c036: {
                    Slugs: [],
                  },
                  character_C028: {
                    Slugs: [],
                  },
                  character_BananaGuard: {
                    Slugs: [],
                  },
                  character_C027: {
                    Slugs: [],
                  },
                  character_C026: {
                    Slugs: [],
                  },
                  character_C020B: {
                    Slugs: [],
                  },
                  character_C025: {
                    Slugs: [],
                  },
                  character_c024: {
                    Slugs: [],
                  },
                  character_C031: {
                    Slugs: [],
                  },
                  character_C029: {
                    Slugs: [],
                  },
                  character_c038: {
                    Slugs: [],
                  },
                  // character_supershaggy: {
                  //   Slugs: [],
                  // },
                },
              },
              DefaultVisibleAssets: {
                CharacterSlugs: getAssetsByType("CharacterData").map((a) => a.slug),
                EmoteSlugs: getAssetsByType("EmoteData").map((a) => a.slug),
                BannerSlugs: getAssetsByType("BannerData").map((a) => a.slug),
                RingoutVfxSlugs: getAssetsByType("RingOutVfxData").map((a) => a.slug),
                ProfileIconSlugs: getAssetsByType("ProfileIconData").map((a) => a.slug),
                AnnouncerPackSlugs: getAssetsByType("AnnouncerPackData").map((a) => a.slug),
                StatTrackerSlugs: getAssetsByType("StatTrackingBundleData").map((a) => a.slug),
                GemSlugs: getAssetsByType("MvsGemHsda").map((a) => a.slug),
                PerkSlugs: getAssetsByType("MvsPerkHsda").map((a) => a.slug),
                SkinSlugsByCharacter: getAllSkinsByChar(),
                TauntSlugsByCharacter: getAllTauntsByChar(),
              },
              StatTrackersThatRequireProgress: {},
              OwnedByDefaultInventoryItems: getAllAssets().map((a) => a.slug),
            },
            AssetMetaData: {
              CharacterMetaData: {
                character_wonder_woman: {
                  MasteryRewardTrack: "mrt_mastery_wonder_woman",
                  DefaultSkin: "skin_wonder_woman_default",
                  DisplayName: "Wonder Woman",
                },
                character_velma: {
                  MasteryRewardTrack: "mrt_mastery_velma",
                  DefaultSkin: "skin_velma_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Mage",
                      "TS:Fixed:Universe:ScoobyDoo",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:Eyewear",
                      "TS:Dynamic:PremieredBeforeThe80s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Human",
                      "TS:Dynamic:RedClothing",
                      "TS:Dynamic:OrangeClothing",
                      "TS:Fixed:Velma",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Dynamic",
                    ],
                  },
                  DisplayName: "Velma",
                },
                character_tom_and_jerry: {
                  MasteryRewardTrack: "mrt_mastery_tom_and_jerry",
                  DefaultSkin: "skin_tom_and_jerry_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Mage",
                      "TS:Fixed:FighterDifficulty:high",
                      "TS:Fixed:Universe:TomandJerry",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:PremieredBeforeThe80s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:Fuzzy",
                      "TS:Fixed:TomAndJerry",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                    ],
                  },
                  DisplayName: "Tom & Jerry",
                },
                character_superman: {
                  MasteryRewardTrack: "mrt_mastery_c003",
                  DefaultSkin: "skin_superman_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Tank",
                      "TS:Fixed:Universe:DC",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Dynamic:Caped",
                      "TS:Dynamic:PremieredBeforeThe80s",
                      "TS:Dynamic:ComicInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:ExtraTerrestrial",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:RedClothing",
                      "TS:Dynamic:YellowClothing",
                      "TS:Dynamic:BlueClothing",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:Superman",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Dynamic",
                    ],
                  },
                  DisplayName: "Superman",
                },
                character_steven: {
                  MasteryRewardTrack: "mrt_mastery_steven",
                  DefaultSkin: "skin_steven_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Universe:StevenUniverse",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:Sandals",
                      "TS:Dynamic:PremieredInThe10s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Human",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:YellowClothing",
                      "TS:Dynamic:PinkClothing",
                      "TS:Dynamic:BlueClothing",
                      "TS:Dynamic:TShirt",
                      "TS:Fixed:FighterDifficulty:high",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:Class:Tank",
                      "TS:Fixed:Steven",
                    ],
                    ParentTags: [
                      "TS:Fixed:Universe",
                      "TS:Fixed",
                      "TS",
                      "TS:Dynamic",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Class",
                    ],
                  },
                  DisplayName: "Steven Universe",
                },
                character_shaggy: {
                  MasteryRewardTrack: "mrt_mastery_shaggy",
                  DefaultSkin: "skin_shaggy_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Bruiser",
                      "TS:Fixed:Universe:ScoobyDoo",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:PremieredBeforeThe80s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Human",
                      "TS:Dynamic:GreenClothing",
                      "TS:Dynamic:TShirt",
                      "TS:Fixed:FighterDifficulty:Low",
                      "TS:Dynamic:Detective",
                      "TS:Fixed:Shaggy",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                      "TS:Fixed:FighterDifficulty",
                    ],
                  },
                  DisplayName: "Shaggy",
                },
                character_jake: {
                  MasteryRewardTrack: "mrt_mastery_jake",
                  DefaultSkin: "skin_jake_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Bruiser",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Universe:AdventureTime",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:PremieredInThe10s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:Fuzzy",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:Jake",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                    ],
                  },
                  DisplayName: "Jake",
                },
                character_harleyquinn: {
                  MasteryRewardTrack: "mrt_mastery_harleyquinn",
                  DefaultSkin: "skin_harley_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Assassin",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Universe:DC",
                      "TS:Dynamic:PremieredInThe10s",
                      "TS:Dynamic:ComicInspired",
                      "TS:Dynamic:Human",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:RedClothing",
                      "TS:Dynamic:WhiteClothing",
                      "TS:Dynamic:BlackClothing",
                      "TS:Dynamic:Season:Villainous",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:HarleyQuinn",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                      "TS:Dynamic:Season",
                    ],
                  },
                  DisplayName: "Harley Quinn",
                },
                character_garnet: {
                  MasteryRewardTrack: "mrt_mastery_garnet",
                  DefaultSkin: "skin_garnet_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:Eyewear",
                      "TS:Dynamic:ExtraTerrestrial",
                      "TS:Dynamic:PremieredInThe10s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:YellowClothing",
                      "TS:Dynamic:PurpleClothing",
                      "TS:Dynamic:PinkClothing",
                      "TS:Fixed:Class:Bruiser",
                      "TS:Fixed:FighterDifficulty:Low",
                      "TS:Fixed:Universe:StevenUniverse",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:Garnet",
                    ],
                    ParentTags: [
                      "TS:Dynamic",
                      "TS",
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                    ],
                  },
                  DisplayName: "Garnet",
                },
                character_finn: {
                  MasteryRewardTrack: "mrt_mastery_finn",
                  DefaultSkin: "skin_finn_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Assassin",
                      "TS:Fixed:Universe:AdventureTime",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:SwordWielder",
                      "TS:Dynamic:Headwear",
                      "TS:Dynamic:PremieredInThe10s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Human",
                      "TS:Fixed:FighterDifficulty:Low",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:Finn",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                      "TS:Fixed:FighterDifficulty",
                    ],
                  },
                  DisplayName: "Finn",
                },
                character_creature: {
                  MasteryRewardTrack: "mrt_mastery_creature",
                  DefaultSkin: "skin_creature_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Mage",
                      "TS:Dynamic:PremieredinThe2020s",
                      "TS:Dynamic:PFGOriginal",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:ExtraTerrestrial",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:Fuzzy",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Universe:PlayerFirstGames",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:Reindog",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Dynamic",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                    ],
                  },
                  DisplayName: "Reindog",
                },
                character_C028: {
                  MasteryRewardTrack: "mrt_mastery_c028",
                  DefaultSkin: "skin_c028_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Mage",
                      "TS:Fixed:FighterDifficulty:Low",
                      "TS:Fixed:Universe:DC",
                      "TS:Dynamic:PremieredBeforeThe80s",
                      "TS:Dynamic:ComicInspired",
                      "TS:Dynamic:Human",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:YellowClothing",
                      "TS:Dynamic:BlueClothing",
                      "TS:Dynamic:GreenClothing",
                      "TS:Dynamic:PurpleClothing",
                      "TS:Dynamic:WhiteClothing",
                      "TS:Dynamic:BlackClothing",
                      "TS:Dynamic:Season:Villainous",
                      "TS:Fixed:Joker",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                      "TS:Dynamic:Season",
                    ],
                  },
                  DisplayName: "The Joker",
                },
                character_C023B: {
                  MasteryRewardTrack: "mrt_mastery_c023b",
                  DefaultSkin: "skin_c023b_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Assassin",
                      "TS:Fixed:Universe:Gremlins",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Dynamic:PremieredinThe80s",
                      "TS:Dynamic:MovieInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:Season:Villainous",
                      "TS:Fixed:Stripe",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Dynamic",
                      "TS:Dynamic:Season",
                    ],
                  },
                  DisplayName: "Stripe",
                },
                character_C023A: {
                  MasteryRewardTrack: "mrt_mastery_c023a",
                  DefaultSkin: "skin_c023A_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Mage",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Universe:Gremlins",
                      "TS:Dynamic:PremieredinThe80s",
                      "TS:Dynamic:MovieInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:Fuzzy",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:Gizmo",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                    ],
                  },
                  DisplayName: "Gizmo",
                },
                character_C021: {
                  MasteryRewardTrack: "mrt_mastery_c021",
                  DefaultSkin: "skin_c021_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:FighterDifficulty:high",
                      "TS:Fixed:Universe:DC",
                      "TS:Fixed:Class:Bruiser",
                      "TS:Dynamic:Caped",
                      "TS:Dynamic:PremieredBeforeThe80s",
                      "TS:Dynamic:ComicInspired",
                      "TS:Dynamic:Human",
                      "TS:Dynamic:Rich",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:YellowClothing",
                      "TS:Dynamic:BlackClothing",
                      "TS:Dynamic:Season:Villainous",
                      "TS:Fixed:BlackAdam",
                    ],
                    ParentTags: [
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Fixed:Class",
                      "TS:Dynamic",
                      "TS:Dynamic:Season",
                    ],
                  },
                  DisplayName: "Black Adam",
                },
                character_C020: {
                  MasteryRewardTrack: "mrt_mastery_c020",
                  DefaultSkin: "skin_c020_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Mage",
                      "TS:Fixed:Universe:RickandMorty",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:PremieredInThe10s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Human",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:BlueClothing",
                      "TS:Dynamic:WhiteClothing",
                      "TS:Fixed:FighterDifficulty:high",
                      "TS:Fixed:Rick",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                      "TS:Fixed:FighterDifficulty",
                    ],
                  },
                  DisplayName: "Rick",
                },
                character_c019: {
                  MasteryRewardTrack: "mrt_mastery_c019",
                  DefaultSkin: "skin_c019_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Universe:RickandMorty",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:PremieredInThe10s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Human",
                      "TS:Dynamic:YellowClothing",
                      "TS:Dynamic:BlueClothing",
                      "TS:Dynamic:TShirt",
                      "TS:Fixed:FighterDifficulty:high",
                      "TS:Fixed:Class:Mage",
                      "TS:Fixed:Morty",
                    ],
                    ParentTags: [
                      "TS:Fixed:Universe",
                      "TS:Fixed",
                      "TS",
                      "TS:Dynamic",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Class",
                    ],
                  },
                  DisplayName: "Morty",
                },
                character_C018: {
                  MasteryRewardTrack: "mrt_mastery_c018",
                  DefaultSkin: "skin_c018_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Universe:LooneyTunes",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:Headwear",
                      "TS:Dynamic:PremieredinThe80s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:ExtraTerrestrial",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:RedClothing",
                      "TS:Dynamic:GreenClothing",
                      "TS:Dynamic:WhiteClothing",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Dynamic:Season:Villainous",
                      "TS:Fixed:Class:Mage",
                      "TS:Fixed:Marvin",
                    ],
                    ParentTags: [
                      "TS:Fixed:Universe",
                      "TS:Fixed",
                      "TS",
                      "TS:Dynamic",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Dynamic:Season",
                      "TS:Fixed:Class",
                    ],
                  },
                  DisplayName: "Marvin The Martian",
                },
                character_C017: {
                  MasteryRewardTrack: "mrt_mastery_c017",
                  DefaultSkin: "skin_c017_s01",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Tank",
                      "TS:Fixed:FighterDifficulty:high",
                      "TS:Fixed:Universe:IronGiant",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:PremieredinThe90s",
                      "TS:Dynamic:MovieInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:ExtraTerrestrial",
                      "TS:Dynamic:RedClothing",
                      "TS:Dynamic:YellowClothing",
                      "TS:Dynamic:Metallic",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:IronGiant",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                    ],
                  },
                  DisplayName: "Iron Giant",
                },
                character_c16: {
                  MasteryRewardTrack: "mrt_mastery_lebron",
                  DefaultSkin: "skin_c016_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:PremieredinThe80s",
                      "TS:Dynamic:PremieredinThe2020s",
                      "TS:Dynamic:MovieInspired",
                      "TS:Dynamic:Human",
                      "TS:Dynamic:Rich",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:SportsAttire",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Universe:SpaceJam",
                      "TS:Fixed:Class:Bruiser",
                      "TS:Fixed:LeBron",
                    ],
                    ParentTags: [
                      "TS:Dynamic",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed",
                      "TS:Fixed:Universe",
                      "TS:Fixed:Class",
                    ],
                  },
                  DisplayName: "LeBron James",
                },
                character_taz: {
                  MasteryRewardTrack: "mrt_mastery_taz",
                  DefaultSkin: "skin_taz_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Universe:LooneyTunes",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:PremieredBeforeThe80s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:Fuzzy",
                      "TS:Dynamic:Adult",
                      "TS:Fixed:Class:Assassin",
                      "TS:Fixed:Taz",
                    ],
                    ParentTags: [
                      "TS:Fixed:Universe",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Dynamic",
                      "TS:Fixed:Class",
                    ],
                  },
                  DisplayName: "Taz",
                },
                character_bugs_bunny: {
                  MasteryRewardTrack: "mrt_mastery_bugs_bunny",
                  DefaultSkin: "skin_bugs_bunny_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Mage",
                      "TS:Fixed:Universe:LooneyTunes",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:PremieredBeforeThe80s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:Fuzzy",
                      "TS:Fixed:BugsBunny",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Dynamic",
                    ],
                  },
                  DisplayName: "Bugs Bunny",
                },
                character_batman: {
                  MasteryRewardTrack: "mrt_mastery_batman",
                  DefaultSkin: "skin_batman_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Bruiser",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Universe:DC",
                      "TS:Dynamic:Caped",
                      "TS:Dynamic:Eyewear",
                      "TS:Dynamic:Headwear",
                      "TS:Dynamic:PremieredinThe80s",
                      "TS:Dynamic:ComicInspired",
                      "TS:Dynamic:Human",
                      "TS:Dynamic:Rich",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:BlackClothing",
                      "TS:Dynamic:Detective",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:Batman",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                    ],
                  },
                  DisplayName: "Batman",
                },
                character_arya: {
                  MasteryRewardTrack: "mrt_mastery_arya",
                  DefaultSkin: "skin_arya_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Assassin",
                      "TS:Fixed:Universe:GameOfThrones",
                      "TS:Dynamic:Caped",
                      "TS:Dynamic:SwordWielder",
                      "TS:Dynamic:PremieredInThe10s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Fuzzy",
                      "TS:Dynamic:BlueClothing",
                      "TS:Dynamic:Human",
                      "TS:Fixed:FighterDifficulty:high",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:Arya",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                      "TS:Fixed:FighterDifficulty",
                    ],
                  },
                  DisplayName: "Arya Stark",
                },
                character_Jason: {
                  MasteryRewardTrack: "mrt_mastery_jason",
                  DefaultSkin: "skin_jason_000",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Tank",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Universe:Fridaythe13th",
                      "TS:Dynamic:Spooky",
                      "TS:Dynamic:SwordWielder",
                      "TS:Dynamic:Eyewear",
                      "TS:Dynamic:Headwear",
                      "TS:Dynamic:PremieredinThe80s",
                      "TS:Dynamic:MovieInspired",
                      "TS:Dynamic:Human",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:RedClothing",
                      "TS:Dynamic:WhiteClothing",
                      "TS:Dynamic:BlackClothing",
                      "TS:Dynamic:Undead",
                      "TS:Dynamic:SportsAttire",
                      "TS:Dynamic:Season:Villainous",
                      "TS:Fixed:Jason",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                      "TS:Dynamic:Season",
                    ],
                  },
                  DisplayName: "Jason Voorhees",
                },
                character_BananaGuard: {
                  MasteryRewardTrack: "mrt_mastery_banana_guard",
                  DefaultSkin: "skin_bananaguard_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Universe:AdventureTime",
                      "TS:Dynamic:Animated",
                      "TS:Dynamic:PremieredInThe10s",
                      "TS:Dynamic:TvInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:YellowClothing",
                      "TS:Fixed:Class:Bruiser",
                      "TS:Dynamic:Heroic",
                      "TS:Fixed:FighterDifficulty:Low",
                      "TS:Fixed:BananaGuard",
                    ],
                    ParentTags: [
                      "TS:Fixed:Universe",
                      "TS:Fixed",
                      "TS",
                      "TS:Dynamic",
                      "TS:Fixed:Class",
                      "TS:Fixed:FighterDifficulty",
                    ],
                  },
                  DisplayName: "Banana Guard",
                },
                character_c036: {
                  MasteryRewardTrack: "mrt_mastery_c036",
                  DefaultSkin: "skin_c036",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Class:Bruiser",
                      "TS:Fixed:Universe:Matrix",
                      "TS:Fixed:AgentSmith",
                    ],
                    ParentTags: [
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Class",
                      "TS:Fixed:Universe",
                    ],
                  },
                  DisplayName: "Agent Smith",
                },
                character_C030: {
                  MasteryRewardTrack: "mrt_mastery_c030",
                  DefaultSkin: "skin_c030_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Assassin",
                      "TS:Dynamic:PowerpuffGirls",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:PowerpuffGirls",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Dynamic",
                      "TS:Fixed:FighterDifficulty",
                    ],
                  },
                  DisplayName: "The Powerpuff Girls",
                },
                character_C026: {
                  MasteryRewardTrack: "mrt_mastery_c026",
                  DefaultSkin: "skin_c026_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Bruiser",
                      "TS:Fixed:Universe:SamuraiJack",
                      "TS:Fixed:FighterDifficulty:Low",
                      "TS:Dynamic:SamuraiJack",
                      "TS:Fixed:SamuraiJack",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Dynamic",
                    ],
                  },
                  DisplayName: "Samurai Jack",
                },
                character_c024: {
                  MasteryRewardTrack: "mrt_mastery_c024",
                  DefaultSkin: "skin_c024_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Assassin",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Universe:Beetlejuice",
                      "TS:Fixed:Betelgeuse",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                    ],
                  },
                  DisplayName: "Betelgeuse",
                },
                character_C025: {
                  MasteryRewardTrack: "mrt_mastery_c025",
                  DefaultSkin: "skin_C025_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Class:Mage",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Universe:DC",
                      "TS:Fixed:Raven",
                    ],
                    ParentTags: [
                      "TS:Fixed:Class",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Universe",
                    ],
                  },
                  DisplayName: "Raven",
                },
                character_C027: {
                  MasteryRewardTrack: "mrt_mastery_c027",
                  DefaultSkin: "skin_C027_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Universe:DC",
                      "TS:Dynamic:Heroic",
                      "TS:Dynamic:Headwear",
                      "TS:Dynamic:PremieredinThe2020s",
                      "TS:Dynamic:ComicInspired",
                      "TS:Dynamic:Non-Human",
                      "TS:Dynamic:Adult",
                      "TS:Dynamic:BlackClothing",
                      "TS:Dynamic:YellowClothing",
                      "TS:Dynamic:RedClothing",
                      "TS:Dynamic:RedWhiteandBlueClothing",
                      "TS:Dynamic:CombatWear",
                      "TS:Fixed:Class:Assassin",
                      "TS:Fixed:Nubia",
                    ],
                    ParentTags: [
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Dynamic",
                      "TS:Fixed:Class",
                    ],
                  },
                  DisplayName: "Nubia",
                },
                character_C031: {
                  MasteryRewardTrack: "mrt_mastery_c031",
                  DefaultSkin: "skin_c031_s00",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Universe:AdventureTime",
                      "TS:Fixed:Marceline",
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Class:Bruiser",
                    ],
                    ParentTags: [
                      "TS:Fixed:Universe",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed:Class",
                    ],
                  },
                  DisplayName: "Marceline the Vampire Queen",
                },
                character_c038: {
                  MasteryRewardTrack: "mrt_mastery_c038",
                  DefaultSkin: "C038",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:Universe:LooneyTunes",
                      "TS:Fixed:Class:Bruiser",
                      "TS:Fixed:FighterDifficulty:Low",
                      "TS:Fixed:Lola",
                    ],
                    ParentTags: [
                      "TS:Fixed:Universe",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Class",
                      "TS:Fixed:FighterDifficulty",
                    ],
                  },
                  DisplayName: "Lola Bunny",
                },
                character_C029: {
                  MasteryRewardTrack: "mrt_mastery_c029",
                  DefaultSkin: "c029_default",
                  TagSystemTags: {
                    GameplayTags: [
                      "TS:Fixed:FighterDifficulty:Medium",
                      "TS:Fixed:Universe:DC",
                      "TS:Fixed:Class:Tank",
                      "TS:Fixed:Aquaman",
                    ],
                    ParentTags: [
                      "TS:Fixed:FighterDifficulty",
                      "TS:Fixed",
                      "TS",
                      "TS:Fixed:Universe",
                      "TS:Fixed:Class",
                    ],
                  },
                  DisplayName: "Aquaman",
                },
              },
            },
          },
        },
        "float-settings": {
          _hydra_compressed: {
            ArenaMatchmakingBotTimeout: 500,
            MissionBulkClaimTimeout: 0.5,
            MultiplayMaxPing: 0.25,
          },
        },
      },
    },
    metadata: null,
    return_code: 200,
  };
}
