import { logger } from "./config/logger";
import { INVENTORY_DEFINITIONS } from "./data/inventoryDefs";
import { ENABLED_SKINS } from "./data/skins";
import { connect } from "./database/client";
import { DataAssetModel } from "./database/DataAssets";
import { disabledCharacters, isDisabledChar, isEnabledChar } from "./utils/garbagecan";

const serviceName = "Loader";

const CHARACTER_SLUGS = [
  // "character_supershaggy",
  // "character_Meeseeks",
  // "character_C022",
  "character_arya",
  "character_BananaGuard",
  "character_batman",
  "character_bugs_bunny",
  "character_C017",
  "character_C018",
  "character_c019",
  "character_C020",
  "character_C021",
  "character_C023A",
  "character_C023B",
  "character_c024",
  "character_C025",
  "character_C026",
  "character_C027",
  "character_C028",
  "character_C029",
  "character_C030",
  "character_C031",
  "character_c036",
  "character_c038",
  "character_c16",
  "character_creature",
  "character_finn",
  "character_garnet",
  "character_harleyquinn",
  "character_jake",
  "character_Jason",
  "character_shaggy",
  "character_steven",
  "character_superman",
  "character_taz",
  "character_tom_and_jerry",
  "character_velma",
  "character_wonder_woman",
] as const;

type CharacterSlug = (typeof CHARACTER_SLUGS)[number];

const emotes = [
  "emote_velma_surprised",
  "emote_steven_stars",
  "emote_shaggy_cry",
  "emote_jake_sweat",
  "emote_jake_wink",
  "emote_harley_crazy",
  "emote_harley_mad",
  "emote_garnet_stars",
  "emote_finn_happy",
  "emote_100",
  "emote_burnt_toast",
  "emote_generic_boom",
  "emote_generic_clap",
  "emote_generic_fire",
  "emote_generic_heart",
  "emote_generic_lightning_bolt",
  "emote_jackolanternflames",
  "emote_let_it_snow",
  "emote_poop_smile",
  "emote_toast",
  "emote_toast_butter",
  "emote_black_adam_angry",
  "emote_irongiant_smile",
  "emote_lebron_smile",
  "emote_bugs_bunny_hearts",
  "emote_batman_neutral",
  "emote_pass_the_salt",
  "emote_gg_spray",
  "emote_thanks",
  "emote_respects",
  "emote_bad_joke",
  "emote_batman_firsttry",
  "emote_rebound",
  "emote_reindog_trolldog",
  "emote_harleyww_BirthOfARival",
  "emote_snack_of_champs",
  "emote_question",
  "emote_exclamation",
  "emote_beckon",
  "emote_anger",
  "emote_reindog_pop",
  "emote_winter",
  "emote_c025_tentacles",
  "emote_rock_on",
  "emote_ginger_bat",
  "emote_c017_winter",
  "emote_a_plus",
  "emote_gift",
  "emote_c031_flirting",
  "emote_muscles_check",
  "emote_jake_itsfine",
  "emote_check",
  "emote_c029_fishfinder",
  "emote_c023a_mogwhy",
  "emote_c013_omgglob",
  "emote_c013_noooo",
  "emote_brokenheart",
];

const banners = [
  "banner_3rror_mvs",
  "banner_reward",
  "banner_deluxe_founders",
  "banner_standard_founders",
  "banner_evo_2022",
  "banner_premium_founders",
  "banner_foretold_champion_rare",
  "banner_foretold_champion_legendary",
  "banner_foretold_champion_epic5",
  "banner_foretold_champion_epic4",
  "banner_foretold_champion_epic3",
  "banner_foretold_champion_epic2",
  "banner_foretold_champion_epic",
  "banner_presently_shocked_epic",
  "banner_agent_red_dress_legendary",
  "banner_pizzaslices",
  "banner_jokerhaha",
  "banner_hole_sweet_hole",
  "banner_fromtheashes",
  "banner_zanifeers_last_hope",
  "banner_work_in_progress",
  "banner_wonderwoman_icon",
  "banner_whats_opera_doc",
  "banner_wayne_tower",
  "banner_tree_fort",
  "banner_tools_of_the_trade",
  "banner_the_power_of_love",
  "banner_themiscyra",
  "banner_test",
  "banner_waterfall",
  "banner_superman_icon",
  "banner_steven_planets",
  "banner_stark_icon",
  "banner_stark_banner",
  "banner_scooby_icon",
  "banner_scoobtober",
  "banner_scoobtober_bats",
  "banner_mogwai_knit",
  "banner_lunar_spire",
  "banner_lunarnewyear_23",
  "banner_lovestorm",
  "banner_loony_tunes",
  "banner_lannister_banner",
  "banner_lady_rainicorns_trail",
  "banner_its_harley_quinn_time",
  "banner_iron_giant_blueprint",
  "banner_iron_giant",
  "banner_ice_kingdom",
  "banner_ice_king",
  "banner_hunted_mansion",
  "banner_pfg_snowman",
  "banner_slushy_plushy",
  "banner_chestnuts_not_included",
  "banner_heart_zenifeer",
  "banner_harley_hyena",
  "banner_scarecrow",
  "banner_ghoulcave",
  "banner_deadmoon",
  "banner_ghosts_in_them_there_hills",
  "banner_ghosts_in_them_there_hills_gold",
  "banner_fortress_of_solitude",
  "banner_fire",
  "banner_extratoastie",
  "banner_encore_encore",
  "banner_danger_high_voltage",
  "banner_daily_planet",
  "banner_cupidsvolley",
  "banner_cheesy_temptations",
  "banner_bugs_bunny_tunnel",
  "banner_bravos",
  "banner_batman_icon",
  "banner_housetargaryen_01",
  "banner_valentineonvortex",
  "banner_groovy",
  "banner_arkham_asylum",
  "banner_marvin_wardrobe_v2",
  "banner_beachy_keen",
  "banner_once_a_crystal_gem",
  "banner_shark_teef",
  "banner_lurking_jason",
  "banner_volleyball_tourney",
  "banner_the_killing_juice",
  "banner_frenemies_of_the_deep",
  "banner_default",
  "banner_nitelite",
  "banner_grunge_match",
  "banner_sun",
  "banner_just_a_pitstop",
  "banner_tj_cyber_legendary",
  "banner_superman_cyber_legendary",
  "banner_rickmort_cyber_legendary",
  "banner_harley_cyber_legendary",
  "banner_arya_cyber_legendary",
  "banner_sea",
  "banner_naptime_for_lion",
  "banner_joker_card",
  "banner_bubbles_epic",
  "banner_s2_grandmaster",
  "banner_s1_platinum_pinnacle",
  "banner_s1_master_master",
  "banner_s1_golden_goliath",
  "banner_s1_diamond_destroyer",
  "banner_one_more_time",
  "S3PlatinumPinnacle_Banner",
  "S3MasterMaster_Banner",
  "S3Grandmaster_Banner",
  "S3GoldenGoliath_Banner",
  "S3DiamondDestroyer_Banner",
  "S3BronzeBrawler_Banner",
  "banner_pumpkin_party_rare",
  "banner_heart_legendary",
  "banner_crossover2",
  "banner_crossover1",
  "banner_goin_solo",
  "galaxy2_banner",
  "banner_galaxy1",
  "banner_dod1",
  "banner_dod2",
  "banner_cherry_blossom",
  "banner_ceiling_slammer",
  "banner_bat85",
  "banner_bat85_2",
  "banner_smoke",
  "Banner_Superman_Bulletproof_Leg",
  "banner_screensaver",
  "S3SilverStalwart_Banner",
  "banner_snowstorm",
  "banner_snowflakes_rare",
  "banner_ruben_epic",
  "banner_marcyshouse",
  "banner_magical_rare",
  "banner_hide_and_seek_kitty",
  "banner_balloonspopping",
  "banner_raven_legendary",
  "banner_cave",
  "banner_cavebat_rare",
  "banner_cavebat_legendary",
  "banner_cavebat_epic",
  "banner_cave_uncommon",
  "banner_snowflakes",
  "banner_ruben",
  "banner_raventhrone_rare",
  "banner_raventhrone_legendary",
  "banner_raventhrone_epic",
  "banner_raven_uncommon",
  "banner_raven_rare",
  "banner_marcyshouse_common",
  "banner_magical_uncommon",
  "s4silverstalwart_banner",
  "s4platinumpinnacle_banner",
  "s4mastermaster_banner",
  "s4grandmaster_banner",
  "s4goldengoliath_banner",
  "s4diamonddestroyer_banner",
  "s4bronzebrawler_banner",
  "banner_foghorn",
  "banner_academia_2",
  "banner_academia_1",
  "banner_trigon_2",
  "banner_trigon_1",
  "banner_winter_2",
  "banner_winter",
  "banner_ugly",
  "banner_ugly_2",
  "Banner_Wraithing_Around",
  "banner_wonders_of_themyscira",
  "banner_wbtower",
  "banner_wbtower_epic",
  "banner_smooches_for_grumpy",
  "banner_acid_uncommon",
  "banner_acid",
  "reindog_crystal_banner",
  "s5silverstalwart_banner",
  "s5platinumpinnacle_banner",
  "s5mastermaster_banner",
  "s5grandmaster_banner",
  "s5goldengoliath_banner",
  "s5diamonddestroyer_banner",
  "s5bronzebrawler_banner",
  "banner_perfectplan",
  "banner_old_school_clownin",
  "banner_nymeriaontheprowl_rare",
  "banner_nymeriaontheprowl_legendary",
  "banner_nymeriaontheprowl_epic",
  "banner_sweettunes_legendary",
  "banner_sweettunes_epic",
  "banner_mountainstars",
  "banner_mask_island",
  "banner_marvinstars_rare",
  "banner_marvinstars_legendary",
  "banner_marvinstars_epic",
  "marceline_nighttime_banner",
  "marceline_adventure_banner",
  "banner_like_bodacious",
  "banner_jokers_fun_house",
  "banner_i_am_vengeance",
  "banner_i_am_the_night",
  "banner_hungry_shaggy",
  "banner_he_seems_friendy",
  "banner_halls_of_knowledge",
  "banner_full_court",
  "banner_countingsheeps_uncommon",
  "banner_countingsheeps",
  "banner_contest_for_power",
  "banner_a_city_of_crime",
  "banner_a_chaotic_kinda_love",
  "banner_candykingdom_rare",
  "banner_candykingdom_legendary",
  "banner_candykingdom_epic",
  "banner_ace_chemical",
  "banner_doll",
  "banner_bunpower",
  "banner_s9silverstalwart",
  "banner_s9platinumpinnacle",
  "banner_s9mastermaster",
  "banner_s9grandmaster",
  "banner_s9goldengoliath",
  "banner_s9diamonddestroyer",
  "banner_s9bronzebrawler",
  "banner_s8silverstalwart",
  "banner_s8platinumpinnacle",
  "banner_s8mastermaster",
  "banner_s8grandmaster",
  "banner_s8goldengoliath",
  "banner_s8diamonddestroyer",
  "banner_s8bronzebrawler",
  "banner_s7silverstalwart",
  "banner_s7platinumpinnacle",
  "banner_s7mastermaster",
  "banner_s7grandmaster",
  "banner_s7goldengoliath",
  "banner_s7diamonddestroyer",
  "banner_s7bronzebrawler",
  "banner_s6silverstalwart",
  "banner_s6platinumpinnacle",
  "banner_s6mastermaster",
  "banner_s6grandmaster",
  "banner_s6goldengoliath",
  "banner_s6diamonddestroyer",
  "banner_s6bronzebrawler",
  "banner_s10silverstalwart",
  "banner_s10platinumpinnacle",
  "banner_s10mastermaster",
  "banner_s10grandmaster",
  "banner_s10goldengoliath",
  "banner_s10diamonddestroyer",
  "banner_s10bronzebrawler",
];

const ringouts = [
  "ring_out_vfx_pfg_team",
  "ring_out_vfx_pfg_multiversus",
  "ring_out_vfx_rising_stars",
  "ring_out_vfx_blue_diamond",
  "ring_out_vfx_snowman_sled",
  "ring_out_vfx_black_adams_bolt",
  "ring_out_vfx_wildfire",
  "ring_out_vfx_joker_cards",
  "ring_out_vfx_adam_west",
  "ring_out_vfx_bat_signal",
  "ring_out_vfx_deploy_batwing",
  "ring_out_vfx_blade_of_grass",
  "ring_out_vfx_boom_tube",
  "ring_out_vfx_canonball",
  "ring_out_vfx_two_face_coin",
  "ring_out_vfx_dark_matter",
  "ring_out_vfx_firework_show",
  "ring_out_vfx_fp's_burning_love",
  "ring_out_vfx_gossamer",
  "ring_out_vfx_house_lannister",
  "ring_out_vfx_house_stark",
  "ring_out_vfx_house_Targeryen",
  "ring_out_vfx_green_lantern_finish",
  "ring_out_vfx_halloween_2022",
  "ring_out_vfx_pillar_of_ice",
  "ring_out_vfx_jellybean",
  "ring_out_vfx_king_shark",
  "ring_out_vfx_lasso_of_truth",
  "ring_out_vfx_lava_breath",
  "ring_out_vfx_lightning_ball",
  "ring_out_vfx_lotus_blossom",
  "ring_out_vfx_lunar_rabbit",
  "ring_out_vfx_marcelines_song",
  "ring_out_vfx_monster_tweety",
  "ring_out_vfx_mushroom_explosion",
  "ring_out_vfx_obsidian",
  "ring_out_vfx_omega_beam",
  "ring_out_vfx_oracles_reading",
  "ring_out_vfx_scoobtober_bats",
  "ring_out_vfx_shazam_final",
  "ring_out_vfx_soothing_energy",
  "ring_out_vfx_legendary_soothing_energy",
  "ring_out_vfx_space_kook",
  "ring_out_vfx_sparkler",
  "ring_out_vfx_spikes_bite",
  "ring_out_vfx_spiritual_awakening",
  "ring_out_vfx_gem_bubbles",
  "ring_out_vfx_shield_and_bubbles",
  "ring_out_vfx_stevens_lion",
  "ring_out_vfx_string_lights",
  "ring_out_vfx_sun_scream",
  "ring_out_vfx_supernova",
  "ring_out_vfx_thats_all_folks",
  "ring_out_vfx_toxic_explosion",
  "ring_out_vfx_happy_birday_tweetie",
  "ring_out_vfx_say_your_prayers_varmit",
  "ring_out_vfx_lady_rainicorn_and_rainbows",
  "ring_out_vfx_bitey_boi",
  "ring_out_vfx_ride_the_wave",
  "ring_out_vfx_yeragrandolflag",
  "ring_out_vfx_love_splosion",
  "ring_out_vfx_jungle_jam",
  "ring_out_vfx_default",
  "ring_out_vfx_chroma",
  "ring_out_vfx_split_the_guard",
  "ring_out_vfx_decompiled",
  "ring_out_vfx_slashed",
  "ring_out_vfx_here_comes_a_thought",
  "ring_out_vfx_scooby_snacks",
  "ring_out_vfx_paint_buckets",
  "ring_out_vfx_olympics_set_spike",
  "ring_out_vfx_olympics_the_breakaway",
  "ring_out_vfx_agentsmith_rage",
  "ring_out_vfx_smile",
  "ring_out_vfx_olympics_running",
  "ring_out_vfx_leave_me_alone",
  "ring_out_vfx_divine_dove",
  "ring_out_vfx_cyber_tower",
  "ring_out_vfx_cybercard",
  "ring_out_vfx_salt_shaker",
  "ring_out_vfx_star_explosion",
  "ring_out_vfx_smoke_bomb",
  "ring_out_vfx_sliced_cheese",
  "ring_out_vfx_poppin_out",
  "ring_out_vfx_comic_book_day",
  "ring_out_vfx_monster_reveal",
  "ring_out_vfx_laughing_fish_flood",
  "ROV_HOTD_GetTheWyrm",
  "ring_out_vfx_glitch",
  "ring_out_vfx_gaunt_lets_go",
  "ring_out_vfx_bif_bam_pow",
  "ring_out_vfx_batman_85_anniversary",
  "rov_zinthos",
  "ring_out_vfx_treasure_rabbit",
  "ring_out_vfx_taz_dynamite",
  "rov_rock_the_nightosphere",
  "rov_icebreaker",
  "rov_hypergalactic_energy",
  "rov_holy_night_sword",
  "rov_gone_in_a_slash",
  "ring_out_vfx_firework_ko",
  "ring_out_vfx_explosion",
  "ring_out_vfx_sentinel_capture",
  "ring_out_vfx_velma_getaclue",
  "ring_out_vfx_shaggy_therewolf",
  "ring_out_vfx_nubia",
  "ring_out_vfx_marceline_bat",
  "ring_out_vfx_ghost_train",
  "ring_out_vfx_aquaman_octopus",
  "ring_out_vfx_trident_of_atlan",
  "ring_out_vfx_aquaman",
  "ring_out_vfx_aku_fire",
  "ring_out_vfx_sugar_spice_everything_nice",
  "ring_out_vfx_slime_monster",
  "ring_out_vfx_mutation_arm",
  "ring_out_vfx_mindblower",
  "ring_out_vfx_black_adam",
  "ring_out_vfx_lazer_blast",
  "ring_out_vfx_red_toast_blue_toast",
];

const profiles_icons = [
  "DC_BM_ProfileIcon_KingOfShadows",
  "DC_BM_ProfileIcon_QueenOfCalamity",
  "DC_BM_ProfileIcon_TheJoker_BottomOfTheDeck",
  "DC_BM_ProfileIcon_TheJoker_ClownPrinceOfCrime",
  "DC_SM_ProfileIcon_Superman_ManOfTomorrow",
  "HBO_GOT_ProfileIcon_GameofThronesAstrolabe",
  "PFG_MVS_ProfileIcon_AceOfFluff",
  "profile_icon_amb_gre_gizmo_1",
  "profile_icon_cn_at_finn_adventure_time",
  "WB_IG_ProfileIcon_C017_AGiantShadow",
  "profileicon_bugs_bunny_jack_of_carrots_doc",
  "LunarNewYear2023_PFG_ProfileIcon_GuardianReinddog",
  "LunarNewYear2023_PFG_ProfileIcon_LunarNewYear23",
  "LunarNewYear2023_PFG_ProfileIcon_ToastieLunarNewYear23",
  "LunarNewYear2023_PFG_ProfileIcon_YearOfTheRabbit",
  "profile_icon_as_ram_faces",
  "profile_icon_AS_RAM_Morty_Morty",
  "profile_icon_as_ram_pickle_rick_1",
  "as_ram_profileicon_morty_toxicmorty",
  "profile_icon_as_ram_rick_face_1",
  "profile_icon_bugsbunny_thewabbit",
  "profile_icon_caped_crusader",
  "profile_icon_capstone_arya",
  "profile_icon_capstone_harley",
  "profile_icon_capstone_jake",
  "profile_icon_capstone_reindog",
  "profile_icon_capstone_shaggy",
  "profile_icon_capstone_steven",
  "profile_icon_cn_at_fin_1",
  "profile_icon_cn_at_lady_rainicorn_1",
  "profile_icon_cn_su_star_1",
  "profile_icon_dc_bat_batlogo_1",
  "profile_icon_dc_ba_flyingblackadam",
  "dc_bm_profileicon_harley_niceshotpuddin",
  "dc_sm_profileicon_superman_hope",
  "dc_ww_profileicon_princessdiana",
  "profile_icon_dc_ww_wwlogo_1",
  "profile_icon_default_gold",
  "profile_icon_evo_2022",
  "profile_icon_halloween_2022_black_lantern_superman",
  "profile_icon_halloween_2022_black_lantern_wonderwoman",
  "profile_icon_halloween_2022_HB_SD_Boo",
  "profile_icon_halloween_2022_Scoobtober",
  "profile_icon_halloween_2022_pumpkin_patch",
  "profile_icon_irongiant_nofollowing",
  "profile_icon_pfg_tournament_bronze",
  "profile_icon_pfg_tournament_gold",
  "profile_icon_pfg_tournament_silver",
  "profile_icon_rankedbeta_reward",
  "profileicon_stripe_mogwaistripe",
  "profile_icon_wb_lt_c015",
  "profile_icon_wb_sd_fredstyle",
  "profile_icon_wb_sd_ghost",
  "profile_icon_wb_sd_scooby_snack",
  "profile_icon_wb_sd_spacekook",
  "profileicon_wb_sj_oldschooljam",
  "profile_icon_winter_2022_gizmo_santas_fuzzy_helper",
  "profile_icon_winter_2022_pfg_gingerbread_toast",
  "profile_icon_winter_2022_pfg_lil_toastie",
  "profile_icon_winter_2022_pfg_mvs_snowflake",
  "ValentinesDayEvent2023_PFG_ProfileIcon_HeartofValentiNeon",
  "ValentinesDayEvent2023_PFG_ProfileIcon_TheFluffiestCupid",
  "ValentinesDayEvent2023_PFG_ProfileIcon_ToastieWithTheMostie",
  "ValentinesDayEvent2023_PFG_ProfileIcon_ValentiNeonSurge",
  "ValentinesDayEvent2023_PFG_ProfileIcon_XOXOMVS",
  "profile_icon_winter_2022_greta_gretaclaus",
  "profile_icon_capstone_wonder_woman",
  "profile_icon_capstone_velma",
  "profile_icon_capstone_tom_and_jerry",
  "profile_icon_capstone_superman",
  "profile_icon_cn_su_steven_universe_1",
  "profile_icon_wb_sd_shaggy_1",
  "profile_icon_cn_at_jake_1",
  "profile_icon_dc_bat_harley_1",
  "profile_icon_cn_su_garnet_1",
  "profile_icon_capstone_finn",
  "profile_icon_reindog_1",
  "profile_icon_capstone_stripe",
  "profile_icon_capstone_c023A",
  "profile_icon_capstone_blackadam",
  "profile_icon_capstone_rick",
  "profile_icon_mastery_c019",
  "profileicon_capstone_marvin",
  "profile_icon_capstone_iron_giant",
  "profile_icon_capstone_c016",
  "profile_icon_capstone_taz",
  "profile_icon_capstone_bugs_bunny",
  "profile_icon_dc_bat_batman_1",
  "profile_icon_hbo_got_arya_1",
  "profile_icon_mvs_nom_nom_nom",
  "profile_icon_mvs_beach_day",
  "profile_icon_c035_new_fiends",
  "profile_icon_c010_snorklin_tj",
  "profile_icon_c035_jason_lives",
  "profile_icon_c036_system_enforcer",
  "profile_icon_c036_in_their_sights",
  "profile_icon_c036_data_corrupted",
  "profile_icon_c034_kingdoms_finest",
  "profile_icon_c034_buff_nanner",
  "profile_icon_c009_summer_solstice_punch",
  "profile_icon_c014_summer_jam_jinkies",
  "profile_icon_c001_life_saver__",
  "profile_icon_c001_by_apollos_sunshine",
  "profile_icon_c028_tropi_cool_joker",
  "profile_icon_c011_he_left_his_family_behind",
  "profile_icon_c028_wild_baby",
  "profile_icon_pfg_power_in_waiting_7",
  "profile_icon_pfg_power_in_waiting_6",
  "profile_icon_pfg_power_in_waiting_5",
  "profile_icon_pfg_power_in_waiting_4",
  "profile_icon_pfg_power_in_waiting_3",
  "profile_icon_pfg_power_in_waiting_2",
  "profile_icon_pfg_power_in_waiting_1",
  "profile_icon_default",
  "profile_icon_wb_watertower",
  "profile_icon_wb_sd_scooby_tag",
  "profile_icon_wb_sd_mysterymachine",
  "profile_icon_cn_su_star_2",
  "profile_icon_cn_at_peppermint_butler_1",
  "profile_icon_cn_at_ice_king_1",
  "profile_icon_capstone_garnet",
  "profile_icon_cn_su_garnet_star",
  "WB_LT_ProfileIcon_LookOutBelow",
  "DC_BM_TheJoker_ThatLaughAgain",
  "CN_AT_ProfileIcon_PartyGod",
  "AS_SJ_ProfileIcons_ExtraTHICK",
  "profile_icon_C020_icon_director",
  "profile_icon_C008_hack_n_smash",
  "profile_icon_C019_rogue_agent",
  "profile_icon_c015_tbbfttt",
  "profile_icon_C010_tnj_protocol_activated",
  "profile_icon_c006_stark_slicing_in",
  "WB_LT_ProfileIcon_C018_B",
  "WB_IG_ProfileIcon_C017_YouStay",
  "AS_SJ_ProfileIcons_EyesofaWarrior",
  "AS_SJ_ProfileIcons_CanineLoyalty",
  "profile_icon_c028_a_complex_dynamic",
  "profile_icon_C012_r+s_4eva",
  "profile_icon_C001_shield_of_a_warrior",
  "profile_icon_garnet_in_her_sights",
  "profile_icon_C003_beware_the_solar_powered_man",
  "profile_icon_C015_round_n_round",
  "profile_icon_c024_sandwormin",
  "profile_icon_c024_hangin_with_harry",
  "profile_icon_gameofthrones",
  "WB_IG_ProfileIcon_C017_NewsreelStar",
  "DC_SM_Superman_RighteousAnger",
  "profile_icon_so_it_began",
  "DC_BM_Batman_ProfileIcon_AlwaysPrepared",
  "CN_sd_ProfileIcon_CreepersAbound",
  "CN_sd_ProfileIcon_ClueFindinFashionista",
  "CN_sd_ProfileIcon_ButItHas3Bathrooms",
  "CN_PPG_ProfileIcon_SMOOCH",
  "CN_PPG_ProfileIcon_SMAK",
  "CN_PPG_ProfileIcon_MWAH",
  "profile_icon_c030r",
  "profile_icon_c030g",
  "cn_c030_profile_icon_c030b",
  "profile_icon_galaxy3",
  "profile_icon_galaxy1",
  "profile_icon_galaxy2",
  "profile_icon_galaxy4",
  "profile_icon_crossover5",
  "profile_icon_crossover1",
  "profile_icon_crossover4",
  "profile_icon_crossover3",
  "profile_icon_crossover2",
  "profile_icon_creepincat",
  "profile_icon_boredfighting",
  "profile_icon_MuertosVerse",
  "profile_icon_Cachorreno",
  "profile_icon_ElGuason",
  "cn_c030_profile_icon_nice",
  "profile_icon_batmobile1",
  "profile_icon_YuletideTaz",
  "profile_icon_SW34T3RW34TH3R",
  "WB_LT_ProfileIcon_WatchYerHeadDoc",
  "DC_BM_ProfileIcon_TheJoker_TheHarleuinOfHate",
  "CN_AT_Marceline_ProfileIcon_TheyWereMine",
  "CN_AT_Marceline_ProfileIcon_JamTheNightosphere",
  "CN_AT_Marceline_ProfileIcon_Fangtastic",
  "CN_AT_Marceline_ProfileIcon_BFF",
  "AS_SJ_ProfileIcons_TheZintaris",
  "AS_SJ_ProfileIcons_MadnessofAku",
  "profile_icon_taztransform",
  "profile_icon_downthehatch",
  "profile_icon_mvs",
  "profile_icon_powerbeauty",
  "profile_icon_thelastlaugh",
  "profile_icon_headmastersmight",
  "wb_lt_profileicon_nevermore",
  "wb_lt_profileicon_alleyesonme",
  "profile_icon_lookahereson",
  "profileicon_easya",
  "profileicon_scorned",
  "profileicon_baddad",
  "profile_icon_winter1",
  "profile_icon_winter2",
  "profile_icon_ugly2",
  "profile_icon_ugly1",
  "profile_icon_storm",
  "profile_icon_lo-luvya",
  "profile_icon_lbstyle",
  "profile_icon_toastmeheart",
  "profile_icon_mvsheart",
  "profile_icon_lovebun",
  "profile_icon_ggheart",
  "WB_LT_ProfileIcon_C018_A",
  "WB_IG_ProfileIcon_C017_HeroOfRockwell",
  "HB_TNJ_ProfileIcon_MyCheddarHalf",
  "HB_TAJ_ProfileIcon_URWhatUEat",
  "HB_TAJ_ProfileIcon_AndAllForMe",
  "HBO_GOT_ProfileIcon_TheIronThrone",
  "DC_SM_Superman_ReadyToFight",
  "profile_icon_battle_for_gotham",
  "DC_AM_ProfileIcons_AtlantisAnswers",
  "DC_AM_ProfileIcons_Aqua-Buddies",
  "DC_AM_Aquaman_ProfileIcon_WavesoftheDeep",
  "CN_sd_ProfileIcon_SnackOfChampions",
  "CN_PPG_ProfileIcon_ShellStillKickYourButt",
  "CN_PPG_ProfileIcon_PowerpuffHotline",
  "CN_PPG_ProfileIcon_BashfulBubbles",
  "CN_PPG_ProfileIcon_Adora",
  "CN_AT_ProfileIcon_TheOceanIsScary",
  "CN_AT_ProfileIcon_PureEvil",
  "CN_AT_ProfileIcon_ItWasntMeItWasTheCrown",
  "profile_icon_cn_at_finn_2",
  "profile_icon_blossom",
  "profile_icon_buttercup",
  "profile_icon_bubbles",
];

const announcer_packs = [
  "announcer_pack_wonderwoman_1",
  "announcer_pack_velma_1",
  "announcer_pack_superman_1",
  "announcer_pack_steven_1",
  "announcer_pack_shaggy_1",
  "announcer_pack_jake_1",
  "announcer_pack_harley_1",
  "announcer_pack_garnet_1",
  "announcer_pack_finn_1",
  "announcer_pack_c021_1",
  "announcer_pack_c018_1",
  "announcer_pack_c017_1",
  "announcer_pack_c016_1",
  "announcer_pack_c015_1",
  "announcer_pack_bugs_1",
  "announcer_pack_batman_1",
  "announcer_pack_arya_1",
  "announcer_pack_bmo_1",
  "announcer_pack_ladyrainicorn_1",
  "announcer_pack_c028",
  "announcer_pack_c028_s03",
  "announcer_pack_c034",
  "announcer_pack_default",
  "announcer_pack_c036",
  "announcer_pack_c020_1",
  "announcer_pack_c019_1",
  "announcer_pack_c026",
  "announcer_pack_c024",
  "announcer_pack_rrb",
  "announcer_pack_mjjj",
  "announcer_pack_c030",
  "announcer_pack_c027",
  "announcerpack_c025",
  "announcerpack_c031",
  "announcerpack_fhlh",
  "announcerpack_c029",
  "announcerpack_c038",
];

const stats = [
  "stat_tracking_bundle_evo2022_1st_place",
  "stat_tracking_bundle_evo2022_4th_place",
  "stat_tracking_bundle_evo2022_2nd_place",
  "stat_tracking_bundle_evo2022_3rd_place",
  "stat_tracking_bundle_evo2022_16th_place",
  "stat_tracking_bundle_evo2022_32nd_place",
  "stat_tracking_bundle_evo2022_64th_place",
  "stat_tracking_bundle_evo2022_8th_place",
  "stat_tracking_bundle_valentines_2023_currency",
  "stat_tracking_bundle_vote1team1",
  "stat_tracking_bundle_vote1team2",
  "stat_tracking_tt2_games_played",
  "stat_tracking_bundle_winter_2022_currency",
  "stat_tracking_bundle_arcade_hard_completions",
  "stat_tracking_bundle_S1_pvp_silver",
  "stat_tracking_bundle_S1_pvp_gold",
  "stat_tracking_bundle_S1_pvp_bronze",
  "stat_tracking_bundle_S2_pvp_silver",
  "stat_tracking_bundle_S2_pvp_gold",
  "stat_tracking_bundle_S2_pvp_bronze",
  "stat_tracking_bundle_arya_highest_damage_dealt",
  "stat_tracking_bundle_harley_highest_damage_dealt",
  "stat_tracking_bundle_garnet_highest_damage_dealt",
  "stat_tracking_bundle_finn_highest_damage_dealt",
  "stat_tracking_bundle_c023A_highest_damage_dealt",
  "stat_tracking_bundle_c021_highest_damage_dealt",
  "stat_tracking_bundle_c020_highest_damage_dealt",
  "stat_tracking_bundle_c019_highest_damage_dealt",
  "stat_tracking_bundle_marvin_highest_damage_dealt",
  "stat_tracking_bundle_iron_giant_highest_damage_dealt",
  "stat_tracking_bundle_lebron_highest_damage_dealt",
  "stat_tracking_bundle_c015_highest_damage_dealt",
  "stat_tracking_bundle_bugs_highest_damage_dealt",
  "stat_tracking_bundle_S4_pvp_silver",
  "stat_tracking_bundle_S4_pvp_gold",
  "stat_tracking_bundle_S4_pvp_bronze",
  "stattrackingbundle_arenatop4",
  "stattrackingbundle_arenatop1",
  "stattrackingbundle_arenaringouts",
  "stattracking_c029highestdamagedealt",
  "stattracking_c038highestdamagedealt",
  "stat_tracking_bundle_wonder_woman_highest_damage_dealt",
  "stat_tracking_bundle_velma_highest_damage_dealt",
  "stat_tracking_bundle_tom_and_jerry_highest_damage_dealt",
  "stat_tracking_bundle_superman_highest_damage_dealt",
  "stat_tracking_bundle_steven_highest_damage_dealt",
  "stat_tracking_bundle_shaggy_highest_damage_dealt",
  "stat_tracking_bundle_reindog_highest_damage_dealt",
  "stat_tracking_bundle_wonder_jake_highest_damage_dealt",
  "stat_tracking_bundle_c028_highest_damage_dealt",
  "stattracking_c036highestdamagedealt",
  "stattracking_c035highestdamagedealt",
  "stattracking_c034highestdamagedealt",
  "stat_tracking_bundle_batman_highest_damage_dealt",
  "stat_tracking_bundle_c028_wins",
  "stat_tracking_bundle_arya_ringouts",
  "stat_tracking_bundle_batman_ringouts",
  "stat_tracking_bundle_bugs_ringouts",
  "stat_tracking_bundle_c015_ringouts",
  "stat_tracking_bundle_lebron_ringouts",
  "stat_tracking_bundle_iron_giant_ringouts",
  "stat_tracking_bundle_marvin_ringouts",
  "stat_tracking_bundle_c019_ringouts",
  "stat_tracking_bundle_c020_ringouts",
  "stat_tracking_bundle_c021_ringouts",
  "stat_tracking_bundle_c023A_ringouts",
  "stat_tracking_bundle_c023B_ringouts",
  "stat_tracking_bundle_c028_ringouts",
  "stat_tracking_bundle_finn_ringouts",
  "stat_tracking_bundle_garnet_ringouts",
  "stat_tracking_bundle_harley_ringouts",
  "stat_tracking_bundle_wonder_jake_ringouts",
  "stat_tracking_bundle_reindog_ringouts",
  "stat_tracking_bundle_shaggy_ringouts",
  "stat_tracking_bundle_steven_ringouts",
  "stat_tracking_bundle_superman_ringouts",
  "stat_tracking_bundle_tom_and_jerry_ringouts",
  "stat_tracking_bundle_velma_ringouts",
  "stat_tracking_bundle_wonder_woman_ringouts",
  "stat_tracking_bundle_total_attacks_dodged",
  "stat_tracking_bundle_total_double_ringouts",
  "stat_tracking_bundle_highest_damage_dealt",
  "stat_tracking_bundle_test_maxed_characters",
  "stat_tracking_bundle_test_ringout_leader",
  "stat_tracking_bundle_test_ringout_leader_gold",
  "stat_tracking_bundle_total_ringouts",
  "stat_tracking_bundle_assists",
  "stat_tracking_bundle_wins",
  "stat_tracking_bundle_wonder_woman_wins",
  "stat_tracking_bundle_velma_wins",
  "stat_tracking_bundle_tom_and_jerry_wins",
  "stat_tracking_bundle_superman_wins",
  "stat_tracking_bundle_steven_wins",
  "stat_tracking_bundle_shaggy_wins",
  "stat_tracking_bundle_wonder_jake_wins",
  "stat_tracking_bundle_harley_wins",
  "stat_tracking_bundle_garnet_wins",
  "stat_tracking_bundle_finn_wins",
  "stat_tracking_bundle_reindog_wins",
  "stat_tracking_bundle_c023B_wins",
  "stat_tracking_bundle_c023A_wins",
  "stat_tracking_bundle_c021_wins",
  "stat_tracking_bundle_c020_wins",
  "stat_tracking_bundle_c019_wins",
  "stat_tracking_bundle_marvin_wins",
  "stat_tracking_bundle_iron_giant_wins",
  "stat_tracking_bundle_lebron_wins",
  "stat_tracking_bundle_c015_wins",
  "stat_tracking_bundle_bugs_wins",
  "stat_tracking_bundle_batman_wins",
  "stat_tracking_bundle_arya_wins",
  "stat_tracking_bundle_banana_guard_wins",
  "stat_tracking_bundle_jason_voorhees_wins",
  "stat_tracking_bundle_agent_smith_wins",
  "stat_tracking_bundle_ThePowerInside1",
  "stat_tracking_bundle_ThePowerInside2",
  "stat_tracking_bundle_ThePowerInside3",
  "stat_tracking_bundle_ThePowerInside4",
  "stat_tracking_bundle_ThePowerInside5",
  "stat_tracking_bundle_ThePowerInside6",
  "stat_tracking_bundle_ThePowerInside7",
  "stat_tracking_bundle_default",
  "stat_tracking_bundle_pve_boss_s1_c036",
  "stat_tracking_bundle_pve_boss_s1_c035",
  "stat_tracking_bundle_pve_boss_s1_c028",
  "stat_tracking_bundle_c026_wins",
  "stat_tracking_bundle_wonder_woman_total_damage_dealt",
  "stat_tracking_bundle_velma_total_damage_dealt",
  "stat_tracking_bundle_tom_and_jerry_total_damage_dealt",
  "stat_tracking_bundle_superman_total_damage_dealt",
  "stat_tracking_bundle_steven_total_damage_dealt",
  "stat_tracking_bundle_shaggy_total_damage_dealt",
  "stat_tracking_bundle_reindog_total_damage_dealt",
  "stat_tracking_bundle_wonder_jake_total_damage_dealt",
  "stat_tracking_bundle_harley_total_damage_dealt",
  "stat_tracking_bundle_garnet_total_damage_dealt",
  "stat_tracking_bundle_finn_total_damage_dealt",
  "stat_tracking_bundle_c036_total_damage_dealt",
  "stat_tracking_bundle_c035_total_damage_dealt",
  "stat_tracking_bundle_c034_total_damage_dealt",
  "stat_tracking_bundle_c028_total_damage_dealt",
  "stat_tracking_bundle_c026_total_damage_dealt",
  "stat_tracking_bundle_c023B_total_damage_dealt",
  "stat_tracking_bundle_c023A_total_damage_dealt",
  "stat_tracking_bundle_c021_total_damage_dealt",
  "stat_tracking_bundle_c020_total_damage_dealt",
  "stat_tracking_bundle_c019_total_damage_dealt",
  "stat_tracking_bundle_marvin_total_damage_dealt",
  "stat_tracking_bundle_iron_giant_total_damage_dealt",
  "stat_tracking_bundle_lebron_total_damage_dealt",
  "stat_tracking_bundle_c015_total_damage_dealt",
  "stat_tracking_bundle_bugs_total_damage_dealt",
  "stat_tracking_bundle_batman_total_damage_dealt",
  "stat_tracking_bundle_arya_total_damage_dealt",
  "stat_tracking_bundle_c036_ringouts",
  "stat_tracking_bundle_c035_ringouts",
  "stat_tracking_bundle_c034_ringouts",
  "stat_tracking_bundle_c026_ringouts",
  "stat_tracking_bundle_pve_stars_earned_c026",
  "stat_tracking_bundle_pve_stars_earned_c024",
  "stat_tracking_bundle_ranked_season_two_wins_2v2",
  "stat_tracking_bundle_ranked_season_two_wins_1v1",
  "stat_tracking_bundle_ranked_season_two_characters_in_gold_2v2",
  "stat_tracking_bundle_ranked_season_two_characters_in_gold_1v1",
  "stat_tracking_bundle_c024_wins",
  "stat_tracking_bundle_c024_total_damage_dealt",
  "stat_tracking_bundle_c024_ringouts",
  "stattracking_ranked_seasonthree_rankedwins_2v2",
  "stattracking_ranked_seasonthree_rankedwins_1v1",
  "stattracking_ranked_seasonthree_charactersingold_2v2",
  "stattracking_ranked_seasonthree_charactersingold_1v1",
  "StatTracking_C030Wins",
  "stat_tracking_bundle_c030_total_damage_dealt",
  "stat_tracking_bundle_c030_ringouts",
  "stat_tracking_bundle_c027_wins",
  "stat_tracking_bundle_c027_total_damage_dealt",
  "stat_tracking_bundle_c027_ringouts",
  "stattracking_c025wins",
  "stattracking_c025totaldamagedealt",
  "stattracking_c025ringouts",
  "stattracking_c025highestdamagedealt",
  "stattracking_pve_starsearned_s4c031",
  "stattracking_pve_starsearned_s4c025",
  "stattracking_c031wins",
  "stattracking_c031totaldamagedealt",
  "stattracking_c031ringouts",
  "stattracking_c031highestdamagedealt",
  "stattracking_ranked_seasonfour_rankedwins_2v2",
  "stattracking_ranked_seasonfour_rankedwins_1v1",
  "stattracking_ranked_seasonfour_charactersingold_2v2",
  "stattracking_ranked_seasonfour_charactersingold_1v1",
  "stattracking_pve_starsearned_s5c038",
  "stattracking_pve_starsearned_s5c029",
  "stattracking_c029wins1",
  "stattracking_c029totaldamagedealt",
  "stattracking_c029ringouts",
  "stattracking_c038wins",
  "stattracking_c038totaldamagedealt",
  "stattracking_c038ringouts",
  "stattracking_ranked_seasonfive_rankedwins_2v2",
  "stattracking_ranked_seasonfive_rankedwins_1v1",
  "stattracking_ranked_seasonfive_charactersingold_2v2",
  "stattracking_ranked_seasonfive_charactersingold_1v1",
  "stattracking_ranked_seasonsix_rankedwins_2v2",
  "stattracking_ranked_seasonsix_rankedwins_1v1",
  "stattracking_ranked_seasonsix_charactersingold_2v2",
  "stattracking_ranked_seasonsix_charactersingold_1v1",
];

const gems = [
  "gem_horror_circle_chance_on_hit_ice",
  "gem_digital_circle_on_dodge_lightning_strike",
  "gem_digital_circle_on_dodge_electric_zone",
  "gem_digital_circle_on_dodge_seismic_reactor",
  "gem_digital_circle_on_respawn_armature",
  "gem_digital_circle_walk_to_charge_electric_gauntlets",
  "gem_digital_circle_chance_on_hit_shock",
  "gem_digitalcircle_firstblood",
  "gem_digitalcircle_tauntafterko",
  "gem_circle_digital_additionaljump",
  "gem_horror_square_on_opponent_fatigued_enrage",
  "gem_horror_circle_bandage",
  "gem_horror_circle_chance_on_hit_burnout",
  "gem_horror_circle_evade_boost",
  "gem_horror_circle_share_elemental_debuffs",
  "gem_horror_circle_chance_on_hit_deplete_cooldown",
  "gem_horror_circle_on_dodge_smoke_bomb",
  "gem_horror_circle_damage_aerial",
  "Gem_chaos_circle_two_faces_coin",
  "gem_horror_circle_chance_on_injury_disable_bounce",
  "Gem_chance_on_hit_random_status_effect_per_match",
  "Gem_chaos_circle_on_dodge_reverse_all_projectiles",
  "Gem_chaos_circle_chance_auto_dodge",
  "Gem_chaos_circle_chance_on_hit_critical_hit",
  "Gem_chance_on_spawn_giant_projectiles",
  "Gem_chance_on_spawn_tiny_enemy_projectiles",
  "Gem_on_dodge_black_adam_bubble_shield",
  "gem_digital_square_weaken_bubble_prison",
  "gem_chaos_deal_damage_to_charge_auto_reflect",
  "gem_chaos_out_of_aerial_specials_joker_balloon",
  "gem_discipline_on_dodge_cleanse_fire_ice",
  "gem_discipline_fast_charge_attacks",
  "gem_discipline_armored_charge_attacks",
  "gem_discipline_reflecting_with_charge_attacks",
  "gem_discipline_companion_toasty",
  "gem_discipline_stand_still_rage",
  "gem_discipline_additional_air_evade",
  "gem_discipline_sweet_spot_stun",
  "gem_discipline_intangible_while_invisible",
  "gem_discipline_charge_fire_aura",
  "gem_discipline_charge_attack_tornado",
  "gem_season3_tethercrystal",
  "gem_season3_shieldplacement",
  "gem_season3_fullcharge",
  "gem_season3_firefists",
  "gem_season3_explodingarmor",
  "gem_season3_companion_2",
  "gem_season3_companion_1",
  "gem_season3_bubblearmor",
  "gem_season3_companion_3",
  "gem_season3_anubiscompanion",
  "Gem_season4_educatedondamage",
  "Gem_season4_stancespeedandsize",
  "Gem_season4_stancegravityandsize",
  "Gem_season4_jumpsfromgroundmelee",
  "Gem_season4_megalodogrevenge",
  "Gem_season4_armoredscars",
  "Gem_season4_stancefireandice",
  "Gem_season4_exhaustarmor",
  "Gem_season4_growthspurt",
  "Gem_arena_regen",
  "Gem_arena_defensepower",
  "Gem_arena_attackpower",
  "Gem_arena_vampire",
  "Gem_arena_dodger",
  "Gem_arena_airspecialist",
  "Gem_arena_verticalattackpower",
  "Gem_arena_wallthemout",
  "Gem_arena_empatheticresponse",
  "Gem_arena_cementshoes",
  "Gem_arena_devilishcontract",
  "Gem_arena_whatachicken",
  "Gem_arena_reactiveplating",
  "Gem_arena_punchyobuns",
  "Gem_arena_brainandbrawn",
  "Gem_arena_bladeandshield",
  "Gem_arena_triggerhappy",
  "Gem_arena_iwantyoutohitme",
  "Gem_arena_andanotherone",
  "Gem_arena_thorns",
  "Gem_arena_ringoutheal",
  "Gem_arena_passinggas",
  "Gem_arena_homingrockets",
  "Gem_arena_finishthem",
  "Gem_arena_doubletake",
  "Gem_arena_bulletproofjuggernaut",
  "Gem_arena_rerollshop",
  "Gem_arena_investor",
  "Gem_arena_projectiledamageincrease",
  "Gem_arena_hotandcold",
  "Gem_arena_enragedresponse",
  "Gem_arena_goldsuit",
  "Gem_arena_emptypockets",
  "Gem_season4_thickskin",
  "Gem_arena_embracetheelements",
  "Gem_arena_explosivepanic",
  "Gem_arena_emergencygadget",
  "Gem_arena_hotfoot",
  "Gem_arena_thebiggertheyare",
  "Gem_arena_coldbreeze",
  "Gem_arena_notoutyet",
  "Gem_arena_heroiclanding",
  "Gem_arena_dashingconfidence",
  "Gem_arena_armorcrush",
];

const perks = [
  "perk_char_one_last_zoinks",
  "perk_gen_boxer",
  "perk_team_speed_force_assist",
  "perk_gen_armor_killer",
  "perk_gen_fire_projectile",
  "perk_gen_well_rounded",
  "perk_gen_second_wind_beneath_your_wings",
  "perk_char_HangryMan",
  "perk_gen_collateral_damage",
  "perk_C020_hephaestuswho",
  "perk_C020_squanchinpyrotechnics",
  "perk_C020_sticklermeeseeks",
  "perk_armor_crush",
  "perk_static_electricity",
  "perk_platform_from_dodge",
  "perk_psychic_damage",
  "perk_purest_of_motivations",
  "perk_run_shield",
  "perk_snowball_effect",
  "perk_stronger_than_ever",
  "perk_sturdy_dodger",
  "perk_char_space_invader",
  "perk_C008_confettiexplosion",
  "perk_C008_glovecontrol",
  "perk_C008_smoothmoves",
  "perk_C012_marker",
  "perk_C004_bouncerang",
  "perk_C004_precisiongrapple",
  "perk_C010_dynamitesplit",
  "perk_C010_flyfisher",
  "perk_blackadam_circuit_breaker",
  "perk_blackadam_hierarchy_of_power",
  "perk_arya_betrayal",
  "perk_arya_trophy",
  "perk_C001_grappleofhermes",
  "perk_C001_shieldofathena",
  "perk_c001_whipofhephaestus",
  "perk_C014_knowledgeispower",
  "perk_C014_studied",
  "perk_C003_breaktheice",
  "perk_C003_flamingreentry",
  "perk_C003_sniperpunch",
  "perk_C009_crystalpal",
  "perk_C009_firefluff",
  "perk_C016_hothands_new",
  "perk_C016_forthree",
  "perk_C016_keeppossession_new",
  "perk_C028_balloonperk",
  "perk_C028_cardperk",
  "perk_C012_electricgroove",
  "perk_C013_backpackstrength",
  "perk_C013_goingoutofbusiness",
  "perk_bugsbunny_lingering_love",
  "perk_bugsbunny_comin_through_doc",
  "perk_marvin_redirect",
  "perk_marvin_heat_seekers",
  "perk_dashbreak",
  "perk_C017_wrongsideofthebed",
  "perk_C017_staticdischarge",
  "perk_C017_afterburners",
  "perk_morty_hammer",
  "perk_morty_grenade",
  "perk_C023B_hestheleader",
  "perk_C023B_boomboombounce",
  "perk_taz_iron_stomach",
  "perk_taz_dogpile",
  "perk_C023A_bouncebounceboom",
  "perk_C023A_powercuddle",
  "perk_C005_sticky",
  "perk_C005_staylimberdude",
  "perk_C011_greenthumb",
  "perk_C011_bouncebubble",
  "perk_C023A_rhythmsgonnagetcha",
  "perk_jason_resurrectionist",
  "perk_jason_monstrous_side_step",
  "perk_morty_extra_fleeb_juice",
  "perk_bananaguard_irontemple",
  "perk_bananaguard_icytears",
  "perk_c026_signature2",
  "perk_c026_signature1",
  "perk_c026_signature3",
  "perk_c036_signature_three",
  "perk_c036_signature_one",
  "perk_c036_signature_four",
  "perk_c024_big_bomb",
  "perk_c024_angry_bugs",
  "perk_c024_frightening",
  "perk_gen_gray_health_on_dodge",
  "perk_gen_jump_on_kb",
  "perk_C012_thunderclap",
  "perk_c030_x",
  "perk_c030_dash",
  "perk_nubia_staffmastery",
  "perk_C027_coldsight",
  "perk_c025_homingbird",
  "perk_c025_reflectbubble",
  "perk_c025_earlytrigon",
  "perk_c031_perkdata_windtunnels",
  "perk_c031_perkdata_bard",
  "perk_c031_perkdata_empress",
  "perk_c029_pufftogo",
  "perk_c029_whirlpool",
  "perk_c029_seahorselunge",
  "perk_c038_heavyball",
  "perk_c038_heart_attack",
];

export type TauntsData = {
  [K in CharacterSlug]: CharacterTauntData;
};

interface CharacterTauntData {
  Slugs: string[];
}

const TAUNTS_DATA: TauntsData = {
  // character_C022: {
  //   Slugs: [],
  // },
  // character_supershaggy: {
  //   Slugs: [
  //     "taunt_supershaggy_default",
  //   ],
  // },
  // character_Meeseeks: {
  //   Slugs: [
  //     "taunt_c019_default",
  //   ],
  // },
  character_wonder_woman: {
    Slugs: [
      "taunt_wonder_woman_hands_on_hips",
      "taunt_wonder_woman_weight_lifting",
    ],
  },
  character_velma: {
    Slugs: [
      "taunt_velma_default",
      "taunt_velma_dance",
      "taunt_velma_reading",
      "taunt_velma_beaker",
    ],
  },
  character_tom_and_jerry: {
    Slugs: [
      "taunt_tomandjerry_default",
      "taunt_tomandjerry_hurttoe",
      "taunt_tomandjerry_naptime",
      "taunt_tomandjerry_scaredycat",
    ],
  },
  character_superman: {
    Slugs: [
      "taunt_superman_crack_neck",
      "taunt_superman_hover",
      "taunt_superman_push_ups",
      "taunt_c003_dance",
    ],
  },
  character_steven: {
    Slugs: [
      "taunt_steven_default",
      "taunt_steven_starstruck",
      "taunt_steven_wipegem",
      "taunt_steven_sharethelove",
      "taunt_c011_taunt_music",
      "taunt_steven_strum",
    ],
  },
  character_shaggy: {
    Slugs: [
      "taunt_shaggy_default",
      "taunt_shaggy_kung_fu",
      "taunt_shaggy_nunchucks",
      "taunt_shaggy_shirtrip",
      "taunt_shaggy_jaw",
    ],
  },
  character_jake: {
    Slugs: [
      "taunt_jake_default",
      "taunt_jake_ballet",
      "taunt_jake_dance",
    ],
  },
  character_harleyquinn: {
    Slugs: [
      "taunt_harley_default",
      "taunt_harley_byebye",
      "taunt_harley_onmallet",
      "taunt_harley_wahwah",
    ],
  },
  character_garnet: {
    Slugs: [
      "taunt_garnet_default",
      "taunt_garnet_dance",
      "taunt_garnet_tinycar",
      "taunt_c012_mad_cause_youre_single",
    ],
  },
  character_finn: {
    Slugs: [
      "taunt_finn_baby_default",
      "taunt_finn_dance2",
      "taunt_finn_baby_dance",
      "taunt_finn_chest_pound",
    ],
  },
  character_creature: {
    Slugs: [
      "taunt_creature_default",
      "taunt_creature_tail_wag",
      "taunt_creature_yawn",
      "taunt_creature_pet",
    ],
  },
  character_C030: {
    Slugs: [
      "taunt_c030_default_01",
      "taunt_c030_taunt1",
    ],
  },
  character_C023B: {
    Slugs: [
      "taunt_c023b_default",
      "taunt_c023b_1",
      "taunt_c023b_excuseme",
      "taunt_c023b_stenchtastic",
    ],
  },
  character_C023A: {
    Slugs: [
      "taunt_c023A_default",
      "taunt_c023A_dance",
      "taunt_c023A_umbrella",
      "taunt_c023A_flightoffancy",
      "taunt_c023A_piano",
    ],
  },
  character_C021: {
    Slugs: [
      "taunt_c021_default",
      "taunt_c021_thumbsdown",
      "taunt_c021_Taunt2",
    ],
  },
  character_C020: {
    Slugs: [
      "taunt_c020_taunt_0",
      "taunt_c020_taunt_1",
      "taunt_c020_taunt_2",
      "taunt_c020_taunt_3",
    ],
  },
  character_c019: {
    Slugs: [
      "taunt_c019_default",
      "taunt_c019_headbentover",
      "taunt_c019_listening",
      "taunt_c019_music",
    ],
  },
  character_C018: {
    Slugs: [
      "taunt_c018_default",
      "taunt_c018_Flag",
      "taunt_c018_helmet_shake",
      "taunt_c018_Trumpet",
    ],
  },
  character_C017: {
    Slugs: [
      "taunt_irongiant_default",
      "taunt_irongiant_tease",
      "taunt_irongiant_backscratcher",
      "taunt_c017_wave",
    ],
  },
  character_c16: {
    Slugs: [
      "taunt_c016_default",
      "taunt_c016_salsaDance",
      "taunt_c016_silencer",
      "taunt_c016_ball_sign",
    ],
  },
  character_taz: {
    Slugs: [
      "Taunt_Taz_Default",
      "Taunt_Taz_Hungry",
      "Taunt_Taz_She_Devil_Howl",
      "taunt_c015_tasty_tantrum",
      "taunt_c015_tongue_out",
    ],
  },
  character_bugs_bunny: {
    Slugs: [
      "taunt_bugs_default",
      "taunt_bugs_dance",
      "taunt_bugs_tease",
      "taunt_bugsbunny_toodles_doc",
      "taunt_bugsbunny_piesthelimit",
    ],
  },
  character_batman: {
    Slugs: [
      "taunt_batman_default",
      "taunt_batman_accidental_bomb",
      "taunt_batman_utility_belt",
      "taunt_batman_hot_dog_eating",
    ],
  },
  character_arya: {
    Slugs: [
      "taunt_arya_default",
      "taunt_arya_laugh",
      "taunt_arya_yawn",
      "taunt_c006_curtsy",
    ],
  },
  character_Jason: {
    Slugs: [
      "taunt_jason_default",
      "taunt_jason_moonwalk",
      "taunt_jason_papercut",
      "taunt_jason_beddybye",
    ],
  },
  character_c036: {
    Slugs: [
      "taunt_c036_default",
      "taunt_c036_spoon",
      "taunt_c036_shadestomp",
    ],
  },
  character_C028: {
    Slugs: [
      "Taunt_C028_Default",
      "Taunt_C028_HairComb",
      "taunt_c028_mock",
      "Taunt_C028_Dance",
      "taunt_c028_blah",
    ],
  },
  character_BananaGuard: {
    Slugs: [
      "taunt_bananaguard_default",
      "taunt_bananaguard_mamasaid",
      "taunt_c034_Taunt1",
    ],
  },
  character_C027: {
    Slugs: [
      "taunt_c027_default",
      "taunt_c027_taunt1",
    ],
  },
  character_C026: {
    Slugs: [
      "taunt_C026_default",
      "taunt_c026_samurai_shuffle",
      "taunt_c026_taunt1",
    ],
  },
  character_C025: {
    Slugs: [
      "taunt_c025_default",
      "taunt_c025_taunt1",
    ],
  },
  character_c024: {
    Slugs: [
      "taunt_C024_default",
      "taunt_c024_taunt1",
    ],
  },
  character_C031: {
    Slugs: [
      "taunt_c031_defaulttaunt",
      "taunt_c031_taunt1",
      "taunt_c031_music",
    ],
  },
  character_C029: {
    Slugs: [
      "taunt_c029_defaulttaunt",
      "taunt_c029_secrethandshake",
      "taunt_c029_fishfood",
    ],
  },
  character_c038: {
    Slugs: [
      "taunt_c038_defaulttaunt",
      "taunt_c038_loser",
    ],
  },
};

interface Data {
  AssetPath: string;
  CharacterSlug: string;
  MasteryRewardTrack: string;
  AppliedBuffs: string[];
}

export async function start() {
  await connect();
  logger.info(`[${serviceName}]: Connected to Mongo`);

  logger.info(`[${serviceName}]: Loading Emotes`);
  for (const emote of emotes) {
    const def = INVENTORY_DEFINITIONS[emote as keyof typeof INVENTORY_DEFINITIONS].data as Data;
    const doc = await DataAssetModel.findOneAndUpdate(
      { assetPath: def.AssetPath },
      {
        $set: {
          slug: emote,
          assetType: "EmoteData",
          character_slug: "",
          enabled: true,
          assetPath: def.AssetPath,
        },
      },
      { upsert: true, new: true },
    ).exec();
  }

  logger.info(`[${serviceName}]: Loading Banners`);
  for (const banner of banners) {
    const def = INVENTORY_DEFINITIONS[banner as keyof typeof INVENTORY_DEFINITIONS].data as Data;
    const doc = await DataAssetModel.findOneAndUpdate(
      { assetPath: def.AssetPath },
      {
        $set: {
          slug: banner,
          assetType: "BannerData",
          character_slug: "",
          enabled: true,
          assetPath: def.AssetPath,
        },
      },
      { upsert: true, new: true },
    ).exec();
  }

  logger.info(`[${serviceName}]: Loading ringouts`);
  for (const ringout of ringouts) {
    const def = INVENTORY_DEFINITIONS[ringout as keyof typeof INVENTORY_DEFINITIONS].data as Data;
    const doc = await DataAssetModel.findOneAndUpdate(
      { assetPath: def.AssetPath },
      {
        $set: {
          slug: ringout,
          assetType: "RingOutVfxData",
          character_slug: "",
          enabled: true,
          assetPath: def.AssetPath,
        },
      },
      { upsert: true, new: true },
    ).exec();
  }

  logger.info(`[${serviceName}]: Loading profile icons`);
  for (const pf_icon of profiles_icons) {
    const def = INVENTORY_DEFINITIONS[pf_icon as keyof typeof INVENTORY_DEFINITIONS].data as Data;
    const doc = await DataAssetModel.findOneAndUpdate(
      { assetPath: def.AssetPath },
      {
        $set: {
          slug: pf_icon,
          assetType: "ProfileIconData",
          character_slug: "",
          enabled: true,
          assetPath: def.AssetPath,
        },
      },
      { upsert: true, new: true },
    ).exec();
  }

  logger.info(`[${serviceName}]: Loading announcer packs`);
  for (const ap of announcer_packs) {
    const def = INVENTORY_DEFINITIONS[ap as keyof typeof INVENTORY_DEFINITIONS].data as Data;
    const doc = await DataAssetModel.findOneAndUpdate(
      { assetPath: def.AssetPath },
      {
        $set: {
          slug: ap,
          assetType: "AnnouncerPackData",
          character_slug: "",
          enabled: true,
          assetPath: def.AssetPath,
        },
      },
      { upsert: true, new: true },
    ).exec();
  }

  logger.info(`[${serviceName}]: Loading stat trackers`);
  for (const statTracker of stats) {
    const def = INVENTORY_DEFINITIONS[statTracker as keyof typeof INVENTORY_DEFINITIONS].data as Data;
    const doc = await DataAssetModel.findOneAndUpdate(
      { assetPath: def.AssetPath },
      {
        $set: {
          slug: statTracker,
          assetType: "StatTrackingBundleData",
          character_slug: def.CharacterSlug,
          //enabled: true,
          enabled: isEnabledChar(statTracker),
          assetPath: def.AssetPath,
        },
      },
      { upsert: true, new: true },
    ).exec();
  }

  logger.info(`[${serviceName}]: Loading gems`);
  for (const gem of gems) {
    const def = INVENTORY_DEFINITIONS[gem as keyof typeof INVENTORY_DEFINITIONS].data as Data;
    const doc = await DataAssetModel.findOneAndUpdate(
      { assetPath: def.AssetPath },
      {
        $set: {
          slug: gem,
          assetType: "MvsGemHsda",
          character_slug: "",
          enabled: true,
          assetPath: def.AssetPath,
        },
      },
      { upsert: true, new: true },
    ).exec();
  }

  logger.info(`[${serviceName}]: Loading perks`);
  for (const perk of perks) {
    const def = INVENTORY_DEFINITIONS[perk as keyof typeof INVENTORY_DEFINITIONS].data as Data;
    const doc = await DataAssetModel.findOneAndUpdate(
      { assetPath: def.AppliedBuffs[0] },
      {
        $set: {
          slug: perk,
          assetType: "MvsPerkHsda",
          character_slug: "",
          //enabled: perk === "perk_platform_from_dodge" ? false : true,
          //enabled: isEnabledChar(perk),
          enabled: true,
          assetPath: def.AppliedBuffs[0],
        },
      },
      { upsert: true, new: true },
    ).exec();
  }

  logger.info(`[${serviceName}]: Loading chars`);
  for (const char of CHARACTER_SLUGS) {
    const def = INVENTORY_DEFINITIONS[char as keyof typeof INVENTORY_DEFINITIONS].data as Data;
    const doc = await DataAssetModel.findOneAndUpdate(
      { assetPath: def.AssetPath },
      {
        $set: {
          slug: char,
          assetType: "CharacterData",
          character_slug: "",
          //enabled: true,
          enabled: isEnabledChar(char),
          assetPath: def.AssetPath,
          MasteryRewardTrack: def.MasteryRewardTrack,
        },
      },
      { upsert: true, new: true },
    ).exec();
  }

  logger.info(`[${serviceName}]: Loading Skins`);
  for (const char of Object.keys(ENABLED_SKINS)) {
    if (isDisabledChar(char)) {
      logger.info(`[${serviceName}]: Skipping skins for disabled char: ${char}`);
      continue;
    }
    for (const skin of ENABLED_SKINS[char as keyof typeof ENABLED_SKINS].Slugs) {
      const t = INVENTORY_DEFINITIONS[skin as keyof typeof INVENTORY_DEFINITIONS];

      if (!t)
      {
        logger.info(`[${serviceName}]: No inventory definition for skin: ${skin}`);
        continue;
      }

      const def = t?.data as Data;
      try {
        const doc = await DataAssetModel.findOneAndUpdate(
          { assetPath: def ? def.AssetPath : "NONE" },
          {
            $set: {
              slug: skin,
              assetType: "SkinData",
              character_slug: char,
              enabled: true,
              assetPath: def ? def.AssetPath : "",
            },
          },
          { upsert: true, new: true },
        ).exec();
      }
      catch (error) {
        logger.error(`[${serviceName}]: Error processing skin: ${skin}. Error: ${error}`);
      }

    }
  }

  logger.info(`[${serviceName}]: Loading Taunts`);
  for (const char of Object.keys(TAUNTS_DATA)) {
    if (isDisabledChar(char)) {
      logger.info(`[${serviceName}]: Skipping taunts for disabled char: ${char}`);
      continue;
    }
    for (const taunt of TAUNTS_DATA[char as keyof typeof TAUNTS_DATA].Slugs) {
      const t = INVENTORY_DEFINITIONS[taunt as keyof typeof INVENTORY_DEFINITIONS];

      if (!t)
      {
        logger.info(`[${serviceName}]: No inventory definition for taunt: ${taunt}`);
        continue;
      }

      const def = t?.data as Data;
      try {
        const doc = await DataAssetModel.findOneAndUpdate(
          { assetPath: def ? def.AssetPath : "NONE" },
          {
            $set: {
              slug: taunt,
              assetType: "TauntData",
              character_slug: char,
              enabled: true,
              assetPath: def ? def.AssetPath : "",
            },
          },
          { upsert: true, new: true },
        ).exec();
      }
      catch (error) {
        logger.error(`[${serviceName}]: Error processing taunt: ${taunt}. Error: ${error}`);
      }
    }
  }

  logger.info(`[${serviceName}]: END`);
}

let shuttingDown = false;
function fatal(err: any, origin: string) {
  
  if (shuttingDown)
  {
    return;
  }
  
  shuttingDown = true;

  logger.error(`[${serviceName}]: [FATAL] ${origin}: ${err?.stack || err}`);
  process.exit(1); // non-zero => Docker treats it as failure and restart policy applies
}

process.on("uncaughtException", (reason, promise) => {
  console.error(`[${serviceName}] Unhandled Exception at:`, promise, "reason:", reason);
  // Print full stack trace
  if (reason instanceof Error) {
    fatal(reason, "uncaughtException");
  }
  process.exit(1);
});

process.on("unhandledRejection", (reason, promise) => {
  console.error(`[${serviceName}] Unhandled Rejection at:`, promise, "reason:", reason);
  // Print full stack trace
  if (reason instanceof Error) {
    fatal(reason, "unhandledRejection");
  }
  process.exit(1);
});
start();
