services:
  openversus-webhook:
    env_file: .env
    image: ghcr.io/christopher-conley/webhook-docker/webhook-dind:latest
    networks:
      ovs:
        aliases:
          - openversus_webhook
          - openversus-webhook
          - webhook
    ports:
      - "9001/tcp"
    privileged: true
    restart: unless-stopped
    volumes:
      - /opt/docker/openversus/webhook/hooks.yml:/etc/webhook/hooks.yml
      - /opt/docker/openversus/webhook/scripts:/etc/webhook/scripts
      - /opt/docker/openversus/webhook/log:/var/log/webhook
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  ovs:
    name: ovs
    external: true
